### ISSUE TITLE
Semantic frame tagger throws NotImplementedError: cannot instantiate 'PosixPath' on your system

### ISSUE THREAD

**Issue by Code4SAFrankie** [flairNLP/flair#1052]
**Describe the bug**
The semantic frame tagger throws a "NotImplementedError: cannot instantiate 'PosixPath' on your system" error on Windows 10 when downloading the model.

**To Reproduce**
from flair.models import SequenceTagger
from flair.data import Sentence
sentence = Sentence("Ek bly in Kaapstad .")
frame_tagger = SequenceTagger.load('frame')

2019-08-31 22:58:33,716 loading file C:\Users\User\.flair\models\en-frame-ontonotes-v0.4.pt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\flair\nn.py", line 101, in load
    state = torch.load(f, map_location=flair.device)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\torch\serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\torch\serialization.py", line 573, in _load
    result = unpickler.load()
  File "E:\WPy-3710\python-3.7.1.amd64\Lib\pathlib.py", line 997, in __new__
    % (cls.__name__,))
NotImplementedError: cannot instantiate 'PosixPath' on your system

**Expected behavior**
Expected the semantic frame tagger model to be successfully downloaded.

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: WinPython 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
 - Version [e.g. flair-0.3.2]: flair-0.4.2, torch-1.0.1

**Additional context**
The upos, ner and other models loaded fine. Tried DOS and Jupyter-lab notebook.

**Comment by alanakbik** [comment]
Could you try the current Flair version (0.4.3) to see if the problem is still there?

**Comment by Code4SAFrankie** [comment]
Get the same error with Flair version 0.4.3

```
>>> frame_tagger = SequenceTagger.load('frame')
2019-09-04 18:52:16,073 loading file C:\Users\User\.flair\models\en-frame-ontonotes-v0.4.pt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\flair\nn.py", line 101, in load
    state = torch.load(f, map_location=flair.device)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\torch\serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\torch\serialization.py", line 573, in _load
    result = unpickler.load()
  File "E:\WPy-3710\python-3.7.1.amd64\Lib\pathlib.py", line 997, in __new__
    % (cls.__name__,))
NotImplementedError: cannot instantiate 'PosixPath' on your system
```

**Comment by alanakbik** [comment]
Strange, can you load the other models or does this only affect 'frame'?

**Comment by Code4SAFrankie** [comment]
Only had this issue with `frame`, loaded plenty of other models.

**Comment by eurekaqq** [comment]
@alanakbik  I have the same issue with `frame` and `frame-fast` on windows10 computer.

**Comment by alanakbik** [comment]
@eurekaqq are the other models working for you as well? very strange that this should only affect the frame models and on windows machines only.

**Comment by eurekaqq** [comment]
@alanakbik I have only tried some model, In my testing , only `frame` and `frame-fast` has this problem.
This problem is on windows only, because model is initialized with pathlib for unix.
In my investigation,  I think bug not in code, maybe re-saving the model in windows can solve this problem.

**Comment by Code4SAFrankie** [comment]
@eurekaqq How does one re-save the model?

**Comment by Code4SAFrankie** [comment]
Renamed the file en-frame-ontonotes-v0.4.pt in the directory C:\Users\User\.flair\models and reexecuted the command (it redownloaded the file). It still gives the same error.

**Comment by kallenbachle67903** [comment]
I have the same problem on windows 10 with TextClassifier model. Have you found any solutions?

**Comment by Code4SAFrankie** [comment]
Nope, still stuck I'm afraid.

**Comment by SergenCiftci** [comment]
Got the same error. Did someone found a workaround for the problem?
I'm using Windows 10 and Anaconda as package manager.

**Comment by Code4SAFrankie** [comment]
@SergenCiftci Nothing so far no.

**Comment by alanakbik** [comment]
I've tried the above snippet in some setups (Ubuntu 19.04 and Google Colab) but do not get this error. I think this is Windows-specific and only affects models that use `BytePairEmbeddings`. It's probably related to how `BytePairEmbeddings` and specifically the `BEmb` object are serialized (@bheinzerling have you encountered issues serializing on linux and deserializing on windows?). 

I'm looking into setting up a Windows setup so I can debug this, so I'll try to fix this as soon as my setup is up and running.

**Comment by bheinzerling** [comment]
I have never tried cross-OS serialize-deserialize, but it looks like using concrete paths such as PosixPath or WindowsPath isn't compatible: 

> If you want to manipulate Windows paths on a Unix machine (or vice versa). You cannot instantiate a WindowsPath when running on Unix, but you can instantiate PureWindowsPath.

https://docs.python.org/3/library/pathlib.html#pure-paths

So the right way would probably be something like:
1. convert to PurePosixPath before serialization
2. convert to PosixPath or WindowsPath after deserialization, depending on OS.

Unfortunately, I currently don't have access to a Windows machine to test this :(

**Comment by eurekaqq** [comment]
Hi @bheinzerling , @alanakbik 
I try to hack the pathlib, like below code snippet,

```python
# env is windows10 1909
from flair.models import SequenceTagger
from flair.data import Sentence
import pathlib

temp = pathlib.PosixPath
pathlib.PosixPath = pathlib.WindowsPath

sentence = Sentence("Ek bly in Kaapstad .")
frame_tagger = SequenceTagger.load('frame-fast')
```
It is work.
However, if your path contains non-ASCII, the "sentencepiece" module will get an error as shown below.
OO is non-ascii.
`OSError: Not found: "C:\Users\OO\.flair\embeddings\en\en.wiki.bpe.vs100000.model": No such file or directory Error #2`

**Comment by Code4SAFrankie** [comment]
Your trick got me past this error, but now I'm getting:
```

2020-05-25 18:53:02,729 loading file C:\Users\User\.flair\models\en-frame-ontonotes-v0.4.pt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\flair\nn.py", line 86, in load
    model = cls._init_model_with_state_dict(state)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\flair\models\sequence_tagger_model.py", line 250, in _init_model_with_state_dict
    rnn_type=rnn_type,
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\flair\models\sequence_tagger_model.py", line 201, in __init__
    self.to(flair.device)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\torch\nn\modules\module.py", line 425, in to
    return self._apply(convert)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
    module._apply(fn)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
    module._apply(fn)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\torch\nn\modules\rnn.py", line 137, in _apply
    self._flat_weights = [getattr(self, weight) for weight in self._flat_weights_names]
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\torch\nn\modules\module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'LSTM' object has no attribute '_flat_weights_names'
```

**Comment by alanakbik** [comment]
Can you update to latest Flair?

**Comment by Code4SAFrankie** [comment]
Got it working thanks
