### ISSUE TITLE
Models not backward compatible - AttributeError: 'DocumentRNNEmbeddings' object has no attribute 'use_word_dropout'

### ISSUE THREAD

**Issue by tombburnell** [flairNLP/flair#1215]
**Describe the bug**
I created a model using recent Flair from Github. Then I tried to deploy it using code that was running Flair 0.4.3 and it failed to load the model with the following exception.

```
Traceback (most recent call last):
  File "/Users/tomburnell/github/news-search-mltopics/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tomburnell/github/news-search-mltopics/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tomburnell/github/news-search-mltopics/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tomburnell/github/news-search-mltopics/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/tomburnell/github/news-search-mltopics/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tomburnell/github/news-search-mltopics/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tomburnell/github/news-search-mltopics/api.py", line 37, in topics_predict
    tags = predict.getLabel(text);
  File "/Users/tomburnell/github/news-search-mltopics/predict.py", line 47, in getLabel
    classifier.predict(sentence)
  File "/Users/tomburnell/github/news-search-mltopics/venv/lib/python3.6/site-packages/flair/models/text_classification_model.py", line 155, in predict
    scores = self.forward(batch)
  File "/Users/tomburnell/github/news-search-mltopics/venv/lib/python3.6/site-packages/flair/models/text_classification_model.py", line 80, in forward
    self.document_embeddings.embed(sentences)
  File "/Users/tomburnell/github/news-search-mltopics/venv/lib/python3.6/site-packages/flair/embeddings.py", line 2732, in embed
    if self.use_word_dropout:
  File "/Users/tomburnell/github/news-search-mltopics/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 585, in __getattr__
    type(self).__name__, name))
AttributeError: 'DocumentRNNEmbeddings' object has no attribute 'use_word_dropout'
```

**Comment by alanakbik** [comment]
@tombburnell are you using the current master branch? If not, could you update to the current state? This error should already be fixed, see https://github.com/zalandoresearch/flair/blob/31cc245f45b38dbbc4ddfc0214a2761a45b2b3a9/flair/embeddings.py#L2689

**Comment by tombburnell** [comment]
Ak ok - I guess I'll need to recreate the model. 

I hope you now have test to ensure backward compatibility now so that models trained with current master branch can be used in production with stable code.

**Comment by alanakbik** [comment]
Ah, sorry I think I misunderstood. We tested for backwards compatibility in the sense that models trained with previous versions (0.4.3) can still be deployed with the version on master branch. But not the other way around (models trained on master and deployed with 0.4.3). We'll release 0.4.4 early next week - I am actually currently putting together the release notes - so the problem might solve itself then.
