### ISSUE TITLE
RuntimeError: Cannot pack empty tensors when using CharacterEmbeddings()

### ISSUE THREAD

**Issue by H20Watermelon** [flairNLP/flair#1269]
When I include `CharacterEmbeddings()` as part of the `StackedEmbeddings`, I get a RuntimeError: "**Cannot pack empty tensors**". The code I used that led to the error is below. The version of Flair is 0.4.2. However, the same error occurred when I used the latest version 0.4.4. as well.

```
from flair.data import Corpus
from flair.embeddings import TokenEmbeddings, WordEmbeddings, StackedEmbeddings, PooledFlairEmbeddings, FlairEmbeddings, CharacterEmbeddings
from typing import List
from flair.models import SequenceTagger
from flair.datasets import ColumnCorpus
from flair.models import SequenceTagger
from flair.trainers import ModelTrainer

columns = {0: 'text', 1: 'ner'}
data_folder = r"E:\FlairTraining"
corpus: Corpus = ColumnCorpus(data_folder, columns, train_file = "flair_train.txt", test_file = "flair_test.txt", dev_file = "flair_dev.txt")
tag_dictionary = corpus.make_tag_dictionary(tag_type="ner")
tag_type = "ner"
embedding_types: List[TokenEmbeddings] = [  WordEmbeddings('glove'), CharacterEmbeddings(), FlairEmbeddings('news-forward'), FlairEmbeddings('news-backward'),]
embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)
tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type)

trainer: ModelTrainer = ModelTrainer(tagger, corpus)
trainer.train(r"E:\FlairTraining\Model1", train_with_dev = True, max_epochs=20)

2019-11-11 19:27:30,862 ----------------------------------------------------------------------------------------------------
2019-11-11 19:27:30,862 Evaluation method: MICRO_F1_SCORE
2019-11-11 19:27:34,087 ----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\envs\pytorch\lib\site-packages\flair\trainers\trainer.py", line 197, in train
    loss = self.model.forward_loss(batch)
  File "C:\Anaconda\envs\pytorch\lib\site-packages\flair\models\sequence_tagger_model.py", line 316, in forward_loss
    features = self.forward(sentences)
  File "C:\Anaconda\envs\pytorch\lib\site-packages\flair\models\sequence_tagger_model.py", line 368, in forward
    self.embeddings.embed(sentences)
  File "C:\Anaconda\envs\pytorch\lib\site-packages\flair\embeddings.py", line 145, in embed
    embedding.embed(sentences)
  File "C:\Anaconda\envs\pytorch\lib\site-packages\flair\embeddings.py", line 76, in embed
    self._add_embeddings_internal(sentences)
  File "C:\Anaconda\envs\pytorch\lib\site-packages\flair\embeddings.py", line 906, in _add_embeddings_internal
    character_embeddings, chars2_length
  File "C:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\utils\rnn.py", line 275, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: Cannot pack empty tensors.

```

**Comment by leonweber** [comment]
I'm getting a similar error when my input contains tokens consisting only of a blank:

```python
from flair import datasets, models
from pathlib import Path
import tempfile

from flair.embeddings import CharacterEmbeddings, StackedEmbeddings
from flair.models import SequenceTagger

with tempfile.TemporaryDirectory() as tempdir:
    tempdir = Path(tempdir)
    with (tempdir / 'train.conll').open('w') as f_train:
        f_train.write("Foo  B-Foo\n")
        f_train.write("  O\n")
    corpus = datasets.ColumnCorpus(tempdir, {0: "text", 1: "ner"})

    embedding_types = [CharacterEmbeddings()]

    embeddings = StackedEmbeddings(embeddings=embedding_types)

    tag_dictionary = corpus.make_tag_dictionary(tag_type="ner")
    tagger = SequenceTagger(hidden_size=10, embeddings=embeddings,
                            tag_dictionary=tag_dictionary, tag_type='ner')
    tagger.forward(corpus.get_all_sentences())
```

I think this is because ColumnDataset interprets whitespace tokens as empty strings. @alanakbik do you have a preferred way of fixing this?

**Comment by djstrong** [comment]
I was facing the same problem (spaces was important in my task). I am using `\t` to separate columns and needed to change separator in `ColumnCorpus`.

**Comment by alanakbik** [comment]
Yes, one way would be to change ColumnDataset and ColumnCorpus to accept an optional separator symbol. This would allow us to pass, like @djstrong writes, a '\t' to the corpus constructor. The dataset would then also need to be tab-separated. 

Alternatively, you could filter all whitespace tokens from the dataset. At least our tokenizers don't return whitespaces as separate tokens, and I am not aware of tasks that require empty tokens to be sequence labeled since typically you want labels for words. Is there a special reason that "empty" tokens exist in this dataset?

**Comment by djstrong** [comment]
Keeping whitespaces (as a separate token or joined with a word) allows for keeping match with original text.
Whitespaces are important in tasks involving a source code.

**Comment by alanakbik** [comment]
For matching the original text, we record the offsets of each token, i.e.: 

```python
sentence = Sentence('This is         good  !')
print(sentence.to_original_text())
```

However, multi-whitespaces are currently not used as features in FlairEmbeddings, which assumes all tokens to be separated by exactly one whitespace, so for the coding example this would lead to problematic embeddings. This is something we could/should add to FlairEmbeddings. 

But predictions are currently only possible for tokens, i.e. whitespaces cannot have a prediction.

**Comment by alanakbik** [comment]
@leonweber we recently merged a PR that lets you specify a column delimiter. Does this address your issue?

**Comment by leonweber** [comment]
Thanks a lot! That resolves my issue.
