### ISSUE TITLE
GPU memory linear increasing until OOM when embedding storage mode is GPU

### ISSUE THREAD

**Issue by RichardHWD** [flairNLP/flair#1274]
I try a demo using SequenceTagger and one foward FlairEmbedding in ner, and I set embedding storage mode to GPU. But i found GPU memory linear increasing until OOM, whatever how small batch_size I set, even 4. I am using one 1080ti.

Here is the log:
`Corpus: 75187 train + 9603 dev + 9479 test sentences  ## is that too large?
[b'<unk>', b'O', b'I', b'<START>', b'<STOP>']
2019-11-15 10:22:02,386 ----------------------------------------------------------------------------------------------------
2019-11-15 10:22:02,387 Model: "SequenceTagger(
  (embeddings): StackedEmbeddings(
    (list_embedding_0): FlairEmbeddings(
      (lm): LanguageModel(
        (drop): Dropout(p=0.05, inplace=False)
        (encoder): Embedding(300, 100)
        (rnn): LSTM(100, 2048)
        (decoder): Linear(in_features=2048, out_features=300, bias=True)
      )
    )
  )
  (word_dropout): WordDropout(p=0.05)
  (locked_dropout): LockedDropout(p=0.5)
  (embedding2nn): Linear(in_features=2048, out_features=2048, bias=True)
  (rnn): LSTM(2048, 512, bidirectional=True)
  (linear): Linear(in_features=1024, out_features=5, bias=True)
)"
2019-11-15 10:22:02,387 ----------------------------------------------------------------------------------------------------
2019-11-15 10:22:02,387 Corpus: "Corpus: 75187 train + 9603 dev + 9479 test sentences"
2019-11-15 10:22:02,387 ----------------------------------------------------------------------------------------------------
2019-11-15 10:22:02,387 Parameters:
2019-11-15 10:22:02,387  - learning_rate: "0.01"
2019-11-15 10:22:02,388  - mini_batch_size: "32"
2019-11-15 10:22:02,388  - patience: "3"
2019-11-15 10:22:02,388  - anneal_factor: "0.5"
2019-11-15 10:22:02,388  - max_epochs: "30"
2019-11-15 10:22:02,388  - shuffle: "True"
2019-11-15 10:22:02,388  - train_with_dev: "False"
2019-11-15 10:22:02,388 ----------------------------------------------------------------------------------------------------
2019-11-15 10:22:02,388 Model training base path: "taggers"
2019-11-15 10:22:02,388 ----------------------------------------------------------------------------------------------------
2019-11-15 10:22:02,388 Device: cuda:0
2019-11-15 10:22:02,388 ----------------------------------------------------------------------------------------------------
2019-11-15 10:22:02,388 Embeddings storage mode: gpu
2019-11-15 10:22:02,389 ----------------------------------------------------------------------------------------------------
2019-11-15 10:22:02,595 epoch 1 - iter 0/2350 - loss 1.59615397 - samples/sec: 46181.14
2019-11-15 10:22:34,468 epoch 1 - iter 235/2350 - loss 1.02610726 - samples/sec: 236.27
2019-11-15 10:23:06,957 epoch 1 - iter 470/2350 - loss 0.83694591 - samples/sec: 231.80
2019-11-15 10:23:38,321 epoch 1 - iter 705/2350 - loss 0.74912894 - samples/sec: 240.09
2019-11-15 10:24:13,902 epoch 1 - iter 940/2350 - loss 0.69849941 - samples/sec: 211.58
2019-11-15 10:24:47,120 epoch 1 - iter 1175/2350 - loss 0.66442834 - samples/sec: 226.71
2019-11-15 10:25:19,136 epoch 1 - iter 1410/2350 - loss 0.63892134 - samples/sec: 235.19
2019-11-15 10:25:51,815 epoch 1 - iter 1645/2350 - loss 0.61872841 - samples/sec: 230.44
2019-11-15 10:26:24,448 epoch 1 - iter 1880/2350 - loss 0.60178281 - samples/sec: 230.77
2019-11-15 10:26:57,023 epoch 1 - iter 2115/2350 - loss 0.58759829 - samples/sec: 231.16
Traceback (most recent call last):
  File "train.py", line 41, in <module>
    embeddings_storage_mode='gpu')
  File "/home/wendong/anaconda2/envs/pytorch1.0_SSD/lib/python3.6/site-packages/flair/trainers/trainer.py", line 273, in train
    loss = self.model.forward_loss(batch)
  File "/home/wendong/anaconda2/envs/pytorch1.0_SSD/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 344, in forward_loss
    features = self.forward(data_points)
  File "/home/wendong/anaconda2/envs/pytorch1.0_SSD/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 405, in forward
    self.embeddings.embed(sentences)
  File "/home/wendong/anaconda2/envs/pytorch1.0_SSD/lib/python3.6/site-packages/flair/embeddings.py", line 149, in embed
    embedding.embed(sentences)
  File "/home/wendong/anaconda2/envs/pytorch1.0_SSD/lib/python3.6/site-packages/flair/embeddings.py", line 81, in embed
    self._add_embeddings_internal(sentences)
  File "/home/wendong/anaconda2/envs/pytorch1.0_SSD/lib/python3.6/site-packages/flair/embeddings.py", line 1822, in _add_embeddings_internal
    sentences_padded, self.chars_per_chunk
  File "/home/wendong/anaconda2/envs/pytorch1.0_SSD/lib/python3.6/site-packages/flair/models/language_model.py", line 136, in get_representation
    output = torch.cat(output_parts)
RuntimeError: CUDA out of memory. Tried to allocate 200.00 MiB (GPU 0; 10.92 GiB total capacity; 9.83 GiB already allocated; 173.50 MiB free; 310.89 MiB cached)
`

**Comment by pommedeterresautee** [comment]
GPU storage means you keep in memory the representation of examples already seen (no garbage collection).
So, if you have not enough memory to store your whole dataset, at some point you get a OOM.
