### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '0+cpu' | for info in torch.__version__.split('.'))

### ISSUE THREAD

**Issue by rahulvsharan** [flairNLP/flair#1388]
Issue.:
2020-01-27 14:15:54,846 loading file C:\Users\1025289\.flair\models\en-pos-ontonotes-fast-v0.4.pt
Traceback (most recent call last):
  File ".\fmain.py", line 16, in <module>
    main()
  File ".\fmain.py", line 4, in main
    intent_obj = GET_INTENT(b_preprocess_query=True)
  File "C:\work\python\proj_fai\get_intent.py", line 10, in __init__
    super().__init__(b_preprocess_query=b_preprocess_query)
  File "C:\work\python\proj_fai\model_flair.py", line 24, in __init__
    self._load_flair_model(flair_model)
  File "C:\work\python\proj_fai\model_flair.py", line 30, in _load_flair_model
    self._seq_tag = SequenceTagger.load(flair_model)
  File "C:\Users\1025289\AppData\Local\Programs\Python\Python37\lib\site-packages\flair\nn.py", line 88, in load
    model = cls._init_model_with_state_dict(state)
  File "C:\Users\1025289\AppData\Local\Programs\Python\Python37\lib\site-packages\flair\models\sequence_tagger_model.py", line 273, in _init_model_with_state_dict
    loss_weights=weights,
  File "C:\Users\1025289\AppData\Local\Programs\Python\Python37\lib\site-packages\flair\models\sequence_tagger_model.py", line 217, in __init__
    self.to(flair.device)
  File "C:\Users\1025289\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 425, in to
    return self._apply(convert)
  File "C:\Users\1025289\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
    module._apply(fn)
  File "C:\Users\1025289\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
    module._apply(fn)
  File "C:\Users\1025289\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
    module._apply(fn)
  File "C:\Users\1025289\AppData\Local\Programs\Python\Python37\lib\site-packages\flair\models\language_model.py", line 394, in _apply       
    for info in torch.__version__.split('.'))
  File "C:\Users\1025289\AppData\Local\Programs\Python\Python37\lib\site-packages\flair\models\language_model.py", line 394, in <genexpr>    
    for info in torch.__version__.split('.'))
ValueError: invalid literal for int() with base 10: '0+cpu'

Environment.:
python : 3.76
torch 1.40

Bug as follows:
for info in torch.__version__.split('.'))
ValueError: invalid literal for int() with base 10: '0+cpu'

torch.__version__.split('.') returns below list but it is trying to convert 0+cpu to int which is raising error.
['1', '4', '0+cpu']

Issue in file.:
flair\models\language_model.py
def _apply(self, fn):
        **major, minor, build, *_ = (int(info)
                                for info in torch.__version__.split('.'))**

**Comment by abeermohamed1** [comment]
the same problem here any help please

**Comment by HaniehP** [comment]
Same problem. I don't have a gpu.

**Comment by abeermohamed1** [comment]
any work around?
currently I am trying to setup CUDA hope it will work

**Comment by alanakbik** [comment]
Hi all, @mittalsuraj18 did a PR that should fix this. The PR has just been merged. Could you try installing with: 
```console
pip install --upgrade git+https://github.com/flairNLP/flair.git
```
Instead of the normal pip install. This should fix the error.

**Comment by abeermohamed1** [comment]
@alanakbik and @mittalsuraj18 thank you it is working now appreciated.

**Comment by HaniehP** [comment]
It's working for me too. Thanks guys!

**Comment by mittalsuraj18** [comment]
@alanakbik i think we can close this issue now

**Comment by rahulvsharan** [comment]
Sure you can close this issue

**Comment by kunkaweb** [comment]
Same problem here, but using GPU.

In my enviroment i've used this version of torch: 
pip install torch==1.4.0+cu100 torchvision==0.5.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html

Then, the error was: 
ValueError: invalid literal for int() with base 10: '0+cu100' | for info in torch.__version__.split('.'))
#1388

I've locally edited language_model.py to simply replace the "cu100" string and solved the problem.

I'm not sure what is the best solution to commit, because probably for other users the string can be different from "cu100".

**Comment by alanakbik** [comment]
Hi @kunkaweb, @mittalsuraj18 (thanks!!) did another PR that should fix this. Could you try installing with: 
```console
pip install --upgrade git+https://github.com/flairNLP/flair.git
```
Instead of the normal pip install. This should fix the error.

**Comment by Melothe** [comment]
I can add that this solved the issue for me, although my string is slightly different: `0+cu92` instead of `0+cpu`

**Comment by mittalsuraj18** [comment]
@Melothe glad to hear it
