### ISSUE TITLE
Conflict with serialized CACHE_ROOT

### ISSUE THREAD

**Issue by remidomingues** [flairNLP/flair#1475]
Hello team,

Many thanks for your great work. We have a little issue related to the portability of serialized flair models related to the cache directory used by flair.

We are training and serializing a flair model on a given machine. The user on this machine is `ubuntu`, so the default cache_root is `/home/ubuntu`. However, when loading this model on another machine, using a different user (e.g. `myuser`), it seems that the old cache_root remains written somewhere in the deserialized model.

We have checked the value of `flair.cache_root` which contains the correct user present in the current machine. However, it seems the deserialized model uses the old one, and thus tries to access an inexisting folder.

Do you think it would be possible to override the old cache_root by the current one when loading models?

Note that we do not observe this issue in flair 0.4.3, though it seems to be present in 0.4.4 and 0.4.5. There may be a link with this PR: https://github.com/flairNLP/flair/pull/667

Here is the corresponding stacktrace:
```
downloading https://nlp.h-its.org/bpemb/fr/fr.wiki.bpe.vs100000.model
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2014382/2014382 [00:00<00:00, 2676103.73B/s]
Traceback (most recent call last):
  File "/home/myuser/Documents/src/precatego-ner/ner/model/models.py", line 33, in __init__
    self.model_ner = SequenceTagger.load(model_ner)
  File "/home/myuser/anaconda3/lib/python3.7/site-packages/flair/nn.py", line 101, in load
    state = torch.load(f, map_location=flair.device)
  File "/home/myuser/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/myuser/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "/home/myuser/anaconda3/lib/python3.7/site-packages/bpemb/bpemb.py", line 454, in __setstate__
    str(model_rel_path), cache_dir=state["cache_dir"])
  File "/home/myuser/anaconda3/lib/python3.7/site-packages/bpemb/bpemb.py", line 196, in _load_file
    return http_get(file_url, cached_file, ignore_tardir=True)
  File "/home/myuser/anaconda3/lib/python3.7/site-packages/bpemb/util.py", line 45, in http_get
    outfile.parent.mkdir(exist_ok=True, parents=True)
  File "/home/myuser/anaconda3/lib/python3.7/pathlib.py", line 1262, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/myuser/anaconda3/lib/python3.7/pathlib.py", line 1262, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/myuser/anaconda3/lib/python3.7/pathlib.py", line 1262, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/myuser/anaconda3/lib/python3.7/pathlib.py", line 1258, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/ubuntu'
```
Many thanks!

**Comment by remidomingues** [comment]
Any feedback on that matter?

Best regards,
Rémi

**Comment by alanakbik** [comment]
We have a branch online that possible fixes this. Could you try if [this works for you](https://github.com/flairNLP/flair/tree/GH-1563-serializable-bpe)?
