### ISSUE TITLE
Pooling operation related error in SequenceTagger training

### ISSUE THREAD

**Issue by alperen-degirmenci-2017400255** [flairNLP/flair#1490]
Hi there,
We are working on training a SequenceTagger model. To represent the words, we use the BertEmbeddings. While configuring the BertEmbeddings in our training script, if we choose the **pooling operation** as **first**, there are no errors. But if we pick the **mean** as a pooling operation, we have the following error:
```
Traceback (most recent call last):
  File "train.py", line 406, in <module>
    main()
  File "train.py", line 330, in main
    train(params, tagger, corpus)
  File "train.py", line 197, in train
    embeddings_in_memory=True)
  File
"/media/disk/home/alperen.degirmenci/.virtualenvs/kanarya-env/lib/python3.6/site-packages/flair/trainers/trainer.py",
 line 150, in train
    loss = self.model.forward_loss(batch)
File
"/media/disk/home/alperen.degirmenci/.virtualenvs/kanarya-env/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py",
 line 262, in forward_loss
    features, lengths, tags = self.forward(sentences, sort=sort)
  File
"/media/disk/home/alperen.degirmenci/.virtualenvs/kanarya-env/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py",
 line 315, in forward
    self.embeddings.embed(sentences)
  File
"/media/disk/home/alperen.degirmenci/.virtualenvs/kanarya-env/lib/python3.6/site-packages/flair/embeddings.py",
 line 130, in embed
    embedding.embed(sentences)
  File
"/media/disk/home/alperen.degirmenci/.virtualenvs/kanarya-env/lib/python3.6/site-packages/flair/embeddings.py",
 line 63, in embed
    self._add_embeddings_internal(sentences)
File
"/media/disk/home/alperen.degirmenci/.virtualenvs/kanarya-env/lib/python3.6/site-packages/flair/embeddings.py",
 line 1184, in _add_embeddings_internal
    mean = torch.mean(torch.cat(embeddings, dim=0), dim=0)
RuntimeError: expected a non-empty list of Tensors
```
**Flair version: 0.4.1**
What might be the reason for this? Any help is appreciated. Many thanks.
Greetings.

**Comment by mlej8** [comment]
Hi I am also encountering a similar issue, could you please let me know if you have solved this issue ?
