### ISSUE TITLE
Got Error When Inference NER model

### ISSUE THREAD

**Issue by vmoudyp** [flairNLP/flair#1553]
I already have a model, but when i try to do inference, i got these error :
```

2020-04-28 18:19:06,716 loading file D:/code/python/spasi/ner/modelling/final-model.pt
Traceback (most recent call last):
  File "D:\code\python\spasi\envs\lib\site-packages\flair\nn.py", line 86, in load
    state = torch.load(f, map_location=flair.device)
  File "D:\code\python\spasi\envs\lib\site-packages\torch\serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\code\python\spasi\envs\lib\site-packages\torch\serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "D:\code\python\spasi\envs\lib\site-packages\torch\serialization.py", line 665, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "D:\code\python\spasi\envs\lib\site-packages\torch\serialization.py", line 740, in restore_location
    return default_restore_location(storage, str(map_location))
  File "D:\code\python\spasi\envs\lib\site-packages\torch\serialization.py", line 156, in default_restore_location
    result = fn(storage, location)
  File "D:\code\python\spasi\envs\lib\site-packages\torch\serialization.py", line 136, in _cuda_deserialize
    return storage_type(obj.size())
  File "D:\code\python\spasi\envs\lib\site-packages\torch\cuda\__init__.py", line 480, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 94.00 MiB (GPU 0; 2.00 GiB total capacity; 1.44 GiB already allocated; 76.34 MiB free; 1.49 GiB reserved in total by PyTorch)
```

and this is the script i used :

```
from flair.data import Sentence
from flair.models import SequenceTagger

model = SequenceTagger.load('D:/code/python/spasi/ner/modelling/final-model.pt')

sentence = Sentence('Saya tinggal di Jakarta')

# predict tags and print
model.predict(sentence)

print(sentence.to_tagged_string())

```

**Comment by djstrong** [comment]
You have to less memory on GPU.

**Comment by vmoudyp** [comment]
When i try without GPU, i got this :

(env) wsl2@DESKTOP-IMIC00D:~/code$ python inference_ner.py
2020-04-28 19:07:08,433 loading file /home/wsl2/model/final-model.pt
Traceback (most recent call last):
  File "inference_ner.py", line 4, in <module>
    model = SequenceTagger.load('/home/wsl2/model/final-model.pt')
  File "/home/wsl2/env/lib/python3.6/site-packages/flair/nn.py", line 88, in load
    model = cls._init_model_with_state_dict(state)
  File "/home/wsl2/env/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 273, in _init_model_with_state_dict
    loss_weights=weights,
  File "/home/wsl2/env/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 217, in __init__
    self.to(flair.device)
  File "/home/wsl2/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 443, in to
    return self._apply(convert)
  File "/home/wsl2/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/home/wsl2/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/home/wsl2/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/wsl2/env/lib/python3.6/site-packages/flair/models/language_model.py", line 394, in _apply
    for info in torch.__version__.split('.'))
  File "/home/wsl2/env/lib/python3.6/site-packages/flair/models/language_model.py", line 394, in <genexpr>
    for info in torch.__version__.split('.'))
ValueError: invalid literal for int() with base 10: '0+cpu'

**Comment by djstrong** [comment]
You need to update flair.

**Comment by vmoudyp** [comment]
Already upgrade (0.4.5) but the problem still remain..

**Comment by alanakbik** [comment]
@vmoudyp I think the second issue is the same as #1528 - did you install a PyTorch CPU-only version? If you have a GPU that is not necessary, you can always deactivate the GPU in flair by doing 

```python
import flair, torch
flair.device = torch.device('cpu')
```
before your code.

Regarding the first problem with the GPU memory errors: It looks like your model is so large that it does not fit into your GPU memory. Did you train it on a different machine? What embeddings are you using?

**Comment by vmoudyp** [comment]
> @vmoudyp I think the second issue is the same as #1528 - did you install a PyTorch CPU-only version? If you have a GPU that is not necessary, you can always deactivate the GPU in flair by doing
> 
> ```python
> import flair, torch
> flair.device = torch.device('cpu')
> ```
> 
> before your code.
> 
> Regarding the first problem with the GPU memory errors: It looks like your model is so large that it does not fit into your GPU memory. Did you train it on a different machine? What embeddings are you using?

Yes, for second issue, i used with CPU-only version.

For first one, yes i used different machine for training and the issue come when i used it on my laptop.

TQ Allan, i will try it first.

**Comment by vmoudyp** [comment]
It work Allan.. TQ.. but i wonder, what happened with second issue.

**Comment by alanakbik** [comment]
The second issue is already fixed in master branch. The fix will be part of the next release of Flair. If you want to run on a CPU-only version before the next release, you can install the current version of Flair from master branch like this:
 ```console
pip install --upgrade git+https://github.com/flairNLP/flair.git
```

**Comment by vmoudyp** [comment]
Ok.. great.. TQ
