### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'labels' in data_fetcher.py

### ISSUE THREAD

**Issue by hanktseng131415go** [flairNLP/flair#1640]
Hi!
When I was following the New Fine-tuneable Transformers suggestion, the below issue arises. It seems like the data_fetcher.py doesn't follow the new format of Sentence(), right?
```
Traceback (most recent call last):
  File "block_classification.py", line 51, in <module>
    corpus = NLPTaskDataFetcher.load_classification_corpus(Path('./'), test_file='test.csv', dev_file='dev.csv', train_file='train.csv')
  File "/home/user/.conda/envs/keras/lib/python3.6/site-packages/deprecated/classic.py", line 233, in wrapper_function
    return wrapped_(*args_, **kwargs_)
  File "/home/user/.conda/envs/keras/lib/python3.6/site-packages/flair/data_fetcher.py", line 452, in load_classification_corpus
    train_file, tokenizer=tokenizer, max_tokens_per_doc=max_tokens_per_doc
  File "/home/user/.conda/envs/keras/lib/python3.6/site-packages/deprecated/classic.py", line 233, in wrapper_function
    return wrapped_(*args_, **kwargs_)
  File "/home/user/.conda/envs/keras/lib/python3.6/site-packages/flair/data_fetcher.py", line 513, in read_text_classification_file
    sentence = Sentence(text, labels=labels, use_tokenizer=tokenizer)
TypeError: __init__() got an unexpected keyword argument 'labels'
```
Or is there anything I missed in my code? The full implementing code is as below:
```
from flair.embeddings import TransformerDocumentEmbeddings
import pandas as pd
from flair.data_fetcher import NLPTaskDataFetcher
from flair.embeddings import DocumentPoolEmbeddings
from flair.models import TextClassifier
from pathlib import Path
from flair.trainers import ModelTrainer
from torch.optim.adam import Adam
import flair, torch

flair.device = torch.device('cuda:0')
training_path = './train.csv'
testing_path = './test.csv'
deving_path = './dev.csv'

corpus = NLPTaskDataFetcher.load_classification_corpus(Path('./'), test_file='test.csv', dev_file='dev.csv', train_file='train.csv')
corpus.test
document_embeddings = TransformerDocumentEmbeddings('xlnet-large-cased', fine_tune = True)
classifier = TextClassifier(document_embeddings, label_dictionary=corpus.make_label_dictionary(), multi_label=True)
trainer = ModelTrainer(classifier, corpus, optimizer=Adam)
trainer.train('./train_hist/', learning_rate=0.1, max_epochs=100, embeddings_storage_mode='gpu')
```
Many thanks

**Comment by alanakbik** [comment]
Hi @hanktseng131415go the `NLPTaskDataFetcher` has been deprecated for a while. Better use the `flair.datasets` methods instead, i.e. the `ClassificationCorpus` as in [this tutorial](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md#reading-a-text-classification-dataset).

**Comment by qijunhui** [comment]
HI, @alanakbik , requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s3.eu-central-1.amazonaws.com', port=443): Max retries exceeded with url: /alan-nlp/resources/embeddings/glove.gensim.vectors.npy (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f42f5cee0b8>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by qijunhui** [comment]
@alanakbik , word_embeddings = [WordEmbeddings("glove"), FlairEmbeddings("news-forward-fast"), FlairEmbeddings("news-backward-fast")]时连接失败

**Comment by UrszulaCzerwinska** [comment]
Hi, I am getting the same error with ColumnCorpus:

```
import os
from flair.data import Corpus
from flair.datasets import ColumnCorpus
from flair.embeddings import *
from flair.trainers import ModelTrainer
from typing import List
from flair.models import SequenceTagger
from flair.trainers import ModelTrainer
import ast
from torch.utils.tensorboard import SummaryWriter


# 1. get the corpus

# define columns
# columns = {0: 'token', 1: 'tag', 2: 'space-after'}
columns = params["corpus"]["columns"]

# this is the folder in which train, test and dev files reside
data_folder = params["corpus"]["data_folder"]

train_file = params["corpus"]["train_file"]
test_file = params["corpus"]["test_file"]
dev_file = params["corpus"]["dev_file"]



# init a corpus using column format, data folder and the names of the train, dev and test files
corpus: Corpus = ColumnCorpus(data_folder, columns,
                              train_file=train_file,
                              test_file=test_file,
                              dev_file=dev_file)

# 2. what tag do we want to predict?
tag_type = 'ner'

# 3. make the tag dictionary from the corpus
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)

# 4. initialize embeddings
embedding_types: List[TokenEmbeddings] =[]

embedding_types.append(TransformerWordEmbeddings(model="camembert-base",
    layers= -1,
    pooling_operation= "mean",
    fine_tune=False,
    allow_long_sentences=True))

```

`
TypeError: __init__() got an unexpected keyword argument 'allow_long_sentences'
`
