### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by nh111** [flairNLP/flair#1681]
Hi thanks for the update,

I tried the updated data.py file, but getting below error again, on below predict syntax.

tagger.predict(sentences)
Traceback (most recent call last):

  File "<ipython-input-9-21efd88a4f4f>", line 1, in <module>
    tagger.predict(sentences)

  File "C:\ProgramData\Anaconda3\lib\site-packages\flair\models\sequence_tagger_model.py", line 362, in predict
    for i, batch in enumerate(dataloader):

  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()

  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration

  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]

  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]

  File "C:\ProgramData\Anaconda3\lib\site-packages\flair\datasets\base.py", line 125, in __getitem__
    return Sentence(text, use_tokenizer=self.use_tokenizer)

  File "C:\ProgramData\Anaconda3\lib\site-packages\flair\data.py", line 499, in __init__
    text = self._restore_windows_1252_characters(text)

  File "C:\ProgramData\Anaconda3\lib\site-packages\flair\data.py", line 847, in _restore_windows_1252_characters
    return re.sub(r"[\u0080-\u0099]", to_windows_1252, text)

  File "C:\ProgramData\Anaconda3\lib\re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)

TypeError: expected string or bytes-like object

_Originally posted by @nh111 in https://github.com/flairNLP/flair/issues/1651#issuecomment-641771734_

**Comment by alanakbik** [comment]
Can you identify the sentence that is causing the error and create a minimal example to reproduce?

**Comment by GiarteDataTeam** [comment]
I got a similar error when importing embedinds. I use Python 3.9 in Windows 11.

`from flair.embeddings import FlairEmbeddings, DocumentPoolEmbeddings, BertEmbeddings, XLNetEmbeddings`

`Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\ProgramData\Anaconda3\envs\SentiAnalysis\lib\site-packages\flair\__init__.py", line 6, in <module>
    from transformers import set_seed as hf_set_seed
  File "C:\ProgramData\Anaconda3\envs\SentiAnalysis\lib\site-packages\transformers\__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "C:\ProgramData\Anaconda3\envs\SentiAnalysis\lib\site-packages\transformers\dependency_versions_check.py", line 36, in <module>
    from .file_utils import is_tokenizers_available
  File "C:\ProgramData\Anaconda3\envs\SentiAnalysis\lib\site-packages\transformers\file_utils.py", line 406, in <module>
    torch_version = version.parse(importlib_metadata.version("torch"))
  File "C:\ProgramData\Anaconda3\envs\SentiAnalysis\lib\site-packages\packaging\version.py", line 49, in parse
    return Version(version)
  File "C:\ProgramData\Anaconda3\envs\SentiAnalysis\lib\site-packages\packaging\version.py", line 264, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object`
