### ISSUE TITLE
Transformers: AttributeError: 'BertTokenizer' object has no attribute 'prepare_for_model'

### ISSUE THREAD

**Issue by stefan-it** [flairNLP/flair#1726]
Hi,

latest version of 🤗 Transformers no longer supports the `prepare_for_model` method, that we're using in our `TransformerWordEmbeddings` class:

https://github.com/flairNLP/flair/blob/8c09e62d9a5a3c227b9ca0fb9f214de9620d4ca0/flair/embeddings/token.py#L957-L960

The following error message is thrown:

```bash
Traceback (most recent call last):
  File "train_conll_en.py", line 58, in <module>
    shuffle=True
  File "/mnt/flair-paper/flair/trainers/trainer.py", line 349, in train
    loss = self.model.forward_loss(batch_step)
  File "/mnt/flair-paper/flair/models/sequence_tagger_model.py", line 599, in forward_loss
    features = self.forward(data_points)
  File "/mnt/flair-paper/flair/models/sequence_tagger_model.py", line 604, in forward
    self.embeddings.embed(sentences)
  File "/mnt/flair-paper/flair/embeddings/token.py", line 71, in embed
    embedding.embed(sentences)
  File "/mnt/flair-paper/flair/embeddings/base.py", line 61, in embed
    self._add_embeddings_internal(sentences)
  File "/mnt/flair-paper/flair/embeddings/token.py", line 892, in _add_embeddings_internal
    self._add_embeddings_to_sentences(batch)
  File "/mnt/flair-paper/flair/embeddings/token.py", line 957, in _add_embeddings_to_sentences
    encoded_inputs = self.tokenizer.prepare_for_model(subtoken_ids_sentence,
AttributeError: 'BertTokenizer' object has no attribute 'prepare_for_model'
```

It should be replaced with `encode_plus` method, see https://github.com/huggingface/transformers/issues/5447.

I'll prepare a PR for that!

**Comment by alanakbik** [comment]
Closed by #1727 - thanks @stefan-it !
