### ISSUE TITLE
Difficulty Implementing CoNLL_03 German NER code

### ISSUE THREAD

**Issue by Crowts** [flairNLP/flair#1913]
I am having trouble running the CoNLL03 German NER code provided [here](https://github.com/flairNLP/flair/blob/master/resources/docs/EXPERIMENTS.md). I'm using data (with original tags I think) that I downloaded from [here](https://github.com/MaviccPRP/ger_ner_evals/tree/master/corpora/conll2003) since I do not have access to the ECI Multilingual Text cd. As a note, I was able to run the English and Dutch implementations successfully.

I believe the problem is with the encoding of the data given the error I am getting (**see below output**)

2020-10-19 02:34:52,234 Reading data from resources/tasks/conll_03_german
2020-10-19 02:34:52,234 Train: resources/tasks/conll_03_german/deu.train
2020-10-19 02:34:52,234 Dev: resources/tasks/conll_03_german/deu.testa
2020-10-19 02:34:52,234 Test: resources/tasks/conll_03_german/deu.testb
Traceback (most recent call last):
  File "train_flair_de.py", line 7, in <module>
    corpus: Corpus = CONLL_03_GERMAN(base_path='resources/tasks')
  File "/opt/anaconda3/envs/flair-venv/lib/python3.8/site-packages/flair/datasets/sequence_labeling.py", line 394, in __init__
    super(CONLL_03_GERMAN, self).__init__(
  File "/opt/anaconda3/envs/flair-venv/lib/python3.8/site-packages/flair/datasets/sequence_labeling.py", line 55, in __init__
    train = ColumnDataset(
  File "/opt/anaconda3/envs/flair-venv/lib/python3.8/site-packages/flair/datasets/sequence_labeling.py", line 162, in __init__
    line = f.readline()
  File "/opt/anaconda3/envs/flair-venv/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 73: invalid continuation byte

Though I suspect this question belongs to a platform like stackoverflow, I've tried a number of fixes from there without success, which led me to open an issue here. I suppose my limited development experience is betraying me but I'd appreciate any help with this. 
Thanks!

**Comment by Crowts** [comment]
I've managed to resolve this issue. After inspecting the **sequence_labeling.py** script again, I realised that I had to explicitly add the encoding set to "latin-1" in the class `CONLL_03_GERMAN(ColumnCorpus)`, specifically as an argument of the `__init__`  function applied to `super(CONLL_03_GERMAN, self)` (lines 394-400). The Dutch and Spanish classes use the same encoding.
