### ISSUE TITLE
DefaultCPUAllocator: can't allocate memory: Cannot allocate memory). Though I have GPUs

### ISSUE THREAD

**Issue by jpainam** [flairNLP/flair#1915]
Hi, I'm using
```
flair: version 0.6.1
pytorch: version 1.5.1
```
And I have four GPUs. I could see one GPU being allocated but then, a few moment later, I get this error
```python
2020-10-20 20:55:51,765 Reading data from data
2020-10-20 20:55:51,765 Train: data/train.txt
2020-10-20 20:55:51,765 Dev: data/dev.txt
2020-10-20 20:55:51,765 Test: data/test.txt
Dictionary with 248337 tags: <unk>, O, title="Alasiri", id="1">, sema, baada_ya, ona, umati, huo, ,, shtuka, na, hapo, mshtakiwa, wa_kwanza, amba, ndiye, fikishwa, mahakama, ambia, toa, pesa, la_sivyo, ua, ., , id="2">, CUF, pitia, katibu_mkuu
Traceback (most recent call last):
  File "train.py", line 50, in <module>
    tag_type=tag_type)
  File "/home/fstu1/miniconda3/lib/python3.7/site-packages/flair/models/sequence_tagger_model.py", line 221, in __init__
    torch.randn(self.tagset_size, self.tagset_size)
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 246685062276 bytes. Error code 12 (Cannot allocate memory)
```
I don't understand why it defaults to CPU again and tries to allocate 229GB :) that's too much allocation for a CPU

Any helps will be appreciated.

**Comment by jpainam** [comment]
solve!. Was loading the wrong column from the dataset
