### ISSUE TITLE
HunFlair Example - TypeError on tagger.predict

### ISSUE THREAD

**Issue by janesp** [flairNLP/flair#1938]
Trying the HunFlair example as flair newbie and mostly python newbie - everything went fine until predict:

```
>>> tagger.predict(sentence)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peterjanes/.local/share/virtualenvs/flair-7JNMXngw/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 1155, in predict
    embedding_storage_mode="cpu",
  File "/Users/peterjanes/.local/share/virtualenvs/flair-7JNMXngw/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 343, in predict
    dataset=SentenceDataset(reordered_sentences), batch_size=mini_batch_size
  File "/Users/peterjanes/anaconda3/lib/python3.6/typing.py", line 1223, in __new__
    return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)
  File "/Users/peterjanes/anaconda3/lib/python3.6/typing.py", line 1184, in _generic_new
    return base_cls.__new__(cls)
TypeError: Can't instantiate abstract class SentenceDataset with abstract methods is_in_memory
```

MacBook Pro 2019, 64 GB, macOS Catalina 10.15.7
Python 3.6.4 Anaconda in virtual environment pipenv

An guidance would be much appreciated ...Peter

**Comment by janesp** [comment]
Thanks for the quick fix!

I cleared all pipenv packages except the one on aws, then reinstalled flair and scispacy - still the same effect. What else do I have to do get the torch fix locally installed?

**Comment by alanakbik** [comment]
@janesp I'll push the fix to pip shortly! Then you can reinstall and it should work.

**Comment by alanakbik** [comment]
Should work now if you reinstall!

**Comment by janesp** [comment]
Phantastic, @alanakbik, very cool 😎 - many firsts for me: First machine learning application outside the course of Andrew Ng, first NER case, first flair installation 😊 > aiming to analyze electronic health records now and transforming relevant information to FHIR

**Comment by amaralcs** [comment]
Just wanted to add that I encountered this issue using flair==0.6.1 with customly trained model inside docker. Upgrading to 0.7 solved it.
