### ISSUE TITLE
Run flair in pool

### ISSUE THREAD

**Issue by brendan8229** [flairNLP/flair#2006]
I've tried to run a simple flair implementation using pool from multiprocessing. Somehow running gets caught up and doesn't work at all. Does anyone have a suggestion for how to make the simple pool below work as one would expect?

```
from multiprocessing import Pool

from flair.data import Sentence
from flair.models import SequenceTagger
tagger = SequenceTagger.load('ner')

def f(s):
    sentence = Sentence(s)
    tagger.predict(sentence)
    v=''
    for token  in sentence:
       v+=token.get_tag('ner').value
    return v

sentenceList = ['I love Berlin.','My name is Tom Smith.','I work at Aldi.']

print([f(s) for s in sentenceList])

with Pool(3) as p:
    r = p.map(f,sentenceList)
    
print(r)
```

**Comment by whoisjones** [comment]
Hi @brendan8229, trying your script gave me the following error (would be cool if you can provide it next time directly in your issue):

`An attempt has been made to start a new process before the current process has finished its bootstrapping phase.`

This error is due to the fact that python starts processes and is messing up with the global variable __name__. Find here a good blogpost from @HallerPatrick to that: [blogpost](https://www.betterthannothing.blog/blog-posts/why-we-use-if-name-main-in-python)

Here's an example of a working solution just by rearranging your code a little:
```
import itertools
from multiprocessing import Pool

from flair.data import Sentence
from flair.models import SequenceTagger

def f(s, tagger):
    sentence = Sentence(s)
    tagger.predict(sentence)
    v = ''
    for token in sentence:
        v += token.get_tag('ner').value
    return v

if __name__ == "__main__":
    tagger = [SequenceTagger.load('ner')]

    sentenceList = ['I love Berlin.', 'My name is Tom Smith.', 'I work at Aldi.']

    with Pool(3) as p:
        r = p.starmap(f, itertools.product(sentenceList, tagger))

    print(r)

**Comment by brendan8229** [comment]
@whoisjones thank you for your response. After your comment and reading @HallerPatrick I can see that I am dealing with a common error when using pool. However, when I run your code I still have an error. I also have not been able to obtain the RuntimeError despite trying to catch it. Can you please show me how you captured the RuntimeError? The code below still just runs without any response or error message. 


```
import sys,traceback

import itertools
from multiprocessing import Pool

from flair.data import Sentence
from flair.models import SequenceTagger

def f(s, tagger):
    sentence = Sentence(s)
    try:
       tagger.predict(sentence)
    except RuntimeError:
        print("Error:", sys.exc_info()[0])
        raise
    v = ''
    for token in sentence:
        v += token.get_tag('ner').value
    return v

if __name__ == "__main__":
    tagger = [SequenceTagger.load('ner')]

    sentenceList = ['I love Berlin.', 'My name is Tom Smith.', 'I work at Aldi.']

    with Pool(3) as p:
        try:
           r = p.starmap(f, itertools.product(sentenceList, tagger))
           print(r)
        except RuntimeError:
            print("Error:", sys.exc_info()[0])
            raise
```

**Comment by whoisjones** [comment]
Hi @brendan8229, the code above works fine, i just copied your initial code into a script and ran it, that gave me your error. Or do i misunderstood your answer?

**Comment by brendan8229** [comment]
@whoisjones Thank you for the response. Neither your code nor the code that I posted three days ago are working for me. Both just run and I cannot even get an error message. I'm using python 3.7.9 on MacOS and flair 0.6.1. I'm quite stumped as to what is going on. Can you please tell me how you accessed the error?

**Comment by whoisjones** [comment]
ok I am refering the following script, copied it into my IDE and run the script. Not declaring `__name__ == "__main__` in standalone programs end up with recursively importing the entire script which you need differentiate.
```
from multiprocessing import Pool

from flair.data import Sentence
from flair.models import SequenceTagger
tagger = SequenceTagger.load('ner')

def f(s):
    sentence = Sentence(s)
    tagger.predict(sentence)
    v=''
    for token  in sentence:
       v+=token.get_tag('ner').value
    return v

sentenceList = ['I love Berlin.','My name is Tom Smith.','I work at Aldi.']

print([f(s) for s in sentenceList])

with Pool(3) as p:
    r = p.map(f,sentenceList)
    
print(r)
```

This gives me following error:
```
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by brendan8229** [comment]
@whoisjones Thank you for responding one last time. This remains a mystery to me. I've now read a handful of posts about the problem when one doesn't use __name__ == "__main__, yet the examples with this clause still don't work for me when using flair.

**Comment by whoisjones** [comment]
Hi @brendan8229, ok i think we're probably not on the same page. I am talking about your script you posted when you opened that issue. I am talking about that one here:

```
from multiprocessing import Pool

from flair.data import Sentence
from flair.models import SequenceTagger

tagger = SequenceTagger.load('ner')


def f(s):
    sentence = Sentence(s)
    tagger.predict(sentence)
    v = ''
    for token in sentence:
        v += token.get_tag('ner').value
    return v


sentenceList = ['I love Berlin.', 'My name is Tom Smith.', 'I work at Aldi.']

print([f(s) for s in sentenceList])

with Pool(3) as p:
    r = p.map(f, sentenceList)

print(r)
```

I use PyCharm 2020.3 and I simply run your script and the following error comes up:

```
2020-12-18 13:33:15,337 loading file /Users/Jonas/.flair/models/en-ner-conll03-v0.4.pt
['OOS-LOCO', 'OOOB-PERE-PERO', 'OOOS-ORGO']
2020-12-18 13:33:20,836 loading file /Users/Jonas/.flair/models/en-ner-conll03-v0.4.pt
2020-12-18 13:33:20,836 loading file /Users/Jonas/.flair/models/en-ner-conll03-v0.4.pt
2020-12-18 13:33:20,838 loading file /Users/Jonas/.flair/models/en-ner-conll03-v0.4.pt
['OOS-LOCO', 'OOOB-PERE-PERO', 'OOOS-ORGO']
['OOS-LOCO', 'OOOB-PERE-PERO', 'OOOS-ORGO']
['OOS-LOCO', 'OOOB-PERE-PERO', 'OOOS-ORGO']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/Jonas/PycharmProjects/flair/issue.py", line 22, in <module>
    with Pool(3) as p:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```
Are you using also an IDE or something like jupyter notebooks?
My first response and your response are both working correct and are throwing no error. What exactly do you want to reproduce and you are not able to reproduce?
