### ISSUE TITLE
Serialization with a custom BPE Embedding model

### ISSUE THREAD

**Issue by elliotbart** [flairNLP/flair#2064]
**Describe the bug**

When loading `BytePairEmbeddings`, parameter `language` is set to `None`.
This raises errors in the serialization steps with `BPEmbSerializable`.

https://github.com/flairNLP/flair/blob/master/flair/embeddings/token.py

*[l. 1657](https://github.com/flairNLP/flair/blob/master/flair/embeddings/token.py#L1657)*

At `__setstate__`, `state["lang"]` is `None` 

*[l. 1665 - l. 1671](https://github.com/flairNLP/flair/blob/master/flair/embeddings/token.py#L1665)*

Paths cannot be built when writing the binary sentencepiece model.

Here is the traceback when loading a sequence tagger with custom BPE Embeddings:

```python
>>> from flair.models.sequence_tagger_model import *
>>> model = SequenceTagger.load('small_generic_v0_100000/best-model.pt')
2021-01-04 14:30:06,386 loading file small_generic_v0_100000/best-model.pt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python3.7/site-packages/flair/nn.py", line 88, in load
    state = torch.load(f, map_location='cpu')
  File "lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "lib/python3.7/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "lib/python3.7/site-packages/flair/embeddings/token.py", line 1523, in __setstate__
    if not os.path.exists(self.cache_dir / state["lang"]):
  File "lib/python3.7/pathlib.py", line 925, in __truediv__
    return self._make_child((key,))
  File "lib/python3.7/pathlib.py", line 704, in _make_child
    drv, root, parts = self._parse_args(args)
  File "lib/python3.7/pathlib.py", line 658, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**To Reproduce**
Load a SequenceTagger with a custom BytePairEmbeddings model.

**Environment (please complete the following information):**
 - OS : CentOS Linux
 - Version : 0.7
 - Python version: 3.7.9
 - PyTorch version: 1.7.0 + Cuda 9.2
 - Using GPU in script?: True
 - Using distributed or parallel set-up in script?: No

**Comment by UrszulaCzerwinska** [comment]
Hi, I am having exactly the same problem, the model trained with default bpe embeddings (fr) + flair loads fine but for the one with fine tuned ones + flair I get the same error message.
