### ISSUE TITLE
Runing the TARS classifier fails with Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2.

### ISSUE THREAD

**Issue by eddsalkield** [flairNLP/flair#2122]
**Describe the bug**
When running the [zero-shot TARS example](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_10_TRAINING_ZERO_SHOT_MODEL.md#use-case-1-classify-text-without-training-data-zero-shot), flair fails with the following output:

```
2021-02-26 15:03:56,837 https://nlp.informatik.hu-berlin.de/resources/models/tars-base/tars-base.pt not found in cache, downloading to /tmp/tmpq6sg4qze
100%|██████████████████████████████████| 438079177/438079177 [00:14<00:00, 30639589.46B/s]
2021-02-26 15:04:11,232 copying /tmp/tmpq6sg4qze to cache at /home/edd/.flair/models/tars-base.pt
2021-02-26 15:04:11,916 removing temp file /tmp/tmpq6sg4qze
2021-02-26 15:04:12,013 loading file /home/edd/.flair/models/tars-base.pt
Traceback (most recent call last):
  File "tars_classifier.py", line 5, in <module>
    tars = TARSClassifier.load('tars-base')
  File "/home/edd/.cache/pypoetry/virtualenvs/atc-processing--a3Jf3Pl-py3.6/lib/python3.6/site-packages/flair/nn.py", line 88, in load
    state = torch.load(f, map_location='cpu')
  File "/home/edd/.cache/pypoetry/virtualenvs/atc-processing--a3Jf3Pl-py3.6/lib/python3.6/site-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/home/edd/.cache/pypoetry/virtualenvs/atc-processing--a3Jf3Pl-py3.6/lib/python3.6/site-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f79d2e56193 in /home/edd/.cache/pypoetry/virtualenvs/atc-processing--a3Jf3Pl-py3.6/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7f783e1e89eb in /home/edd/.cache/pypoetry/virtualenvs/atc-processing--a3Jf3Pl-py3.6/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::unique_ptr<caffe2::serialize::ReadAdapterInterface, std::default_delete<caffe2::serialize::ReadAdapterInterface> >) + 0x57 (0x7f783e1e9b37 in /home/edd/.cache/pypoetry/virtualenvs/atc-processing--a3Jf3Pl-py3.6/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x6a7685 (0x7f79d3ee1685 in /home/edd/.cache/pypoetry/virtualenvs/atc-processing--a3Jf3Pl-py3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x2961c4 (0x7f79d3ad01c4 in /home/edd/.cache/pypoetry/virtualenvs/atc-processing--a3Jf3Pl-py3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #6: python3() [0x595291]
frame #7: python3() [0x549ce5]
frame #8: python3() [0x551391]
frame #10: python3() [0x50a533]
frame #12: python3() [0x507cd4]
frame #14: python3() [0x595221]
frame #15: python3() [0x549b3f]
frame #16: python3() [0x551391]
frame #18: python3() [0x50a533]
frame #20: python3() [0x507cd4]
frame #21: python3() [0x509a00]
frame #22: python3() [0x50a3fd]
frame #24: python3() [0x5096c8]
frame #25: python3() [0x50a3fd]
frame #27: python3() [0x507cd4]
frame #29: python3() [0x635262]
frame #34: __libc_start_main + 0xe7 (0x7f79d983cb97 in /lib/x86_64-linux-gnu/libc.so.6)
```

**To Reproduce**
Install flair 0.7 in a venv (I used poetry), and run the example code from the docs.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS, kernel 5.4.0
 - Version: flair-0.7

**Comment by stefan-it** [comment]
Hi @eddsalkield ,

could you also specify the used PyTorch version :thinking: maybe it is too old - is it < 1.5.0 :thinking:

**Comment by eddsalkield** [comment]
Thanks, my pytorch version was too old.  This is because it seems there was a dependency issue regarding `torch` on my specific Python version, as on trying to upgrade I got:

```
  The current project's Python requirement (>=3.6,<4.0) is not compatible with some of the required packages Python requirement:
    - torch requires Python >=3.6.2, so it will not be satisfied for Python >=3.6,<3.6.2

  Because torch (==1.7.1) requires Python >=3.6.2
   and no versions of torch match >1.7.1,<2.0.0, torch is forbidden.
  So, because atc-processing depends on torch (>=1.7.1,<2.0.0), version solving failed.
```

The solution was to loosen my requirements for the Python version in my `pyproject.toml`.  I chose `python = ">=3.6.2,<4.0"`.
