### ISSUE TITLE
raise ValueError("check_hostname requires server_hostname") ValueError: check_hostname requires server_hostname

### ISSUE THREAD

**Issue by RAMJIJAISWAL97** [flairNLP/flair#2256]
I am using the glove model for word embedding but I am Error server_hostname require but not able if find any solution.

Traceback (most recent call last):
  File "embadding.py", line 18, in <module>
    glove_embedding = WordEmbeddings('glove')
  File "/home/others/.conda/envs/model/lib/python3.7/site-packages/flair-0.8.1-py3.7.egg/flair/embeddings/token.py", line 138, in __init__
    cached_path(f"{hu_path}/glove.gensim.vectors.npy", cache_dir=cache_dir)
  File "/home/others/.conda/envs/model/lib/python3.7/site-packages/flair-0.8.1-py3.7.egg/flair/file_utils.py", line 91, in cached_path
    return get_from_cache(url_or_filename, dataset_cache)
  File "/home/others/.conda/envs/model/lib/python3.7/site-packages/flair-0.8.1-py3.7.egg/flair/file_utils.py", line 217, in get_from_cache
    response = requests.head(url, headers={"User-Agent": "Flair"}, allow_redirects=True)
  File "/home/others/.conda/envs/model/lib/python3.7/site-packages/requests/api.py", line 104, in head
    return request('head', url, **kwargs)
  File "/home/others/.conda/envs/model/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/others/.conda/envs/model/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/others/.conda/envs/model/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/others/.conda/envs/model/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/others/.conda/envs/model/lib/python3.7/site-packages/urllib3/connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "/home/others/.conda/envs/model/lib/python3.7/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "/home/others/.conda/envs/model/lib/python3.7/site-packages/urllib3/connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "/home/others/.conda/envs/model/lib/python3.7/site-packages/urllib3/connection.py", line 506, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "/home/others/.conda/envs/model/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "/home/others/.conda/envs/model/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "/home/others/.conda/envs/model/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/home/others/.conda/envs/model/lib/python3.7/ssl.py", line 827, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

**Comment by RAMJIJAISWAL97** [comment]
from flair.embeddings import TransformerWordEmbeddings

import pdb

import pickle as pkl

import numpy as np

import re
from flair.embeddings import WordEmbeddings

from flair.embeddings import TransformerWordEmbeddings

from flair.data import Sentence

from scipy.spatial import distance

glove_embedding = WordEmbeddings('glove')
