### ISSUE TITLE
RuntimeError: Already borrowed 

### ISSUE THREAD

**Issue by chandrashekar3792** [flairNLP/flair#2258]
root - ERROR - Exception occurred
Traceback (most recent call last):
  File "/home/social/ner-tagging/social-ner.py", line 27, in predictNER
    tagger.predict(sentence)
  File "/home/social/ner-tagging/lib64/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 379, in predict
    feature = self.forward(batch)
  File "/home/social/ner-tagging/lib64/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 642, in forward
    self.embeddings.embed(sentences)
  File "/home/social/ner-tagging/lib64/python3.6/site-packages/flair/embeddings/base.py", line 60, in embed
    self._add_embeddings_internal(sentences)
  File "/home/social/ner-tagging/lib64/python3.6/site-packages/flair/embeddings/token.py", line 923, in _add_embeddings_internal
    self._add_embeddings_to_sentence(sentence)
  File "/home/social/ner-tagging/lib64/python3.6/site-packages/flair/embeddings/token.py", line 957, in _add_embeddings_to_sentence
    subtokenized_sentence = self.tokenizer.tokenize(tokenized_string)
  File "/home/social/ner-tagging/lib64/python3.6/site-packages/transformers/tokenization_utils_fast.py", line 302, in tokenize
    return self.encode_plus(text=text, text_pair=pair, add_special_tokens=add_special_tokens, **kwargs).tokens()
  File "/home/social/ner-tagging/lib64/python3.6/site-packages/transformers/tokenization_utils_base.py", line 2362, in encode_plus
    **kwargs,
  File "/home/social/ner-tagging/lib64/python3.6/site-packages/transformers/tokenization_utils_fast.py", line 475, in _encode_plus
    **kwargs,
  File "/home/social/ner-tagging/lib64/python3.6/site-packages/transformers/tokenization_utils_fast.py", line 382, in _batch_encode_plus
    pad_to_multiple_of=pad_to_multiple_of,
  File "/home/social/ner-tagging/lib64/python3.6/site-packages/transformers/tokenization_utils_fast.py", line 337, in set_truncation_and_padding
    self._tokenizer.no_truncation()
RuntimeError: Already borrowed

**Comment by chandrashekar3792** [comment]
Error while prdicting NER
`tagger.predict(sentence)`

**Comment by HallerPatrick** [comment]
Could you provide a minimal, reproducible code sample?

**Comment by samhardyhey** [comment]
Main issue detailed [here](https://github.com/huggingface/tokenizers/issues/537).

Issue exists when a model's tokenizer is shared by more than one process; a pretty important production parameter.

**Comment by jroakes** [comment]
Here is a colab with the full example of the issue: https://colab.research.google.com/drive/1GCr4nuasc6I2GeYbeNt6eaE6JPUcfGav?usp=sharing

One solution is to use `use_fast = False`  but this fails due to dependency in the code on `return_offsets_mapping`.

**Comment by ganga7445** [comment]
I know tagger.predict(batch_sentences) is causing the problem because of multiple processors.
how to pass use_fast = False in flair code?
