### ISSUE TITLE
RuntimeError: There were no tensor arguments to this function

### ISSUE THREAD

**Issue by LarsFied** [flairNLP/flair#2353]
**Describe the bug**
While training a model with Textclassifier a pytorch-function throws an RuntimeError. For me it seems to be an incompatibility of the flair and pytorch versions. Is it a bug or am I doing something wrong? 
Here is the console output:

2021-07-27 13:50:47,744 Computing label dictionary. Progress:
100%|██████████| 514/514 [00:06<00:00, 82.85it/s]
2021-07-27 13:50:53,964 [b'5', b'2', b'8', b'0', b'6', b'9', b'4', b'7', b'3', b'1']
2021-07-27 13:50:57,605 ----------------------------------------------------------------------------------------------------
2021-07-27 13:50:57,605 Model: "TextClassifier(
  (document_embeddings): DocumentPoolEmbeddings(
    fine_tune_mode=none, pooling=mean
    (embeddings): StackedEmbeddings(
      (list_embedding_0): WordEmbeddings('D:\Transfer\flair\de-wiki-fasttext-300d-1M')
    )
  )
  (decoder): Linear(in_features=300, out_features=10, bias=True)
  (loss_function): CrossEntropyLoss()
  (beta): 1.0
  (weights): None
  (weight_tensor) None
)"
2021-07-27 13:50:57,605 ----------------------------------------------------------------------------------------------------
2021-07-27 13:50:57,605 Corpus: "Corpus: 385 train + 129 dev + 129 test sentences"
2021-07-27 13:50:57,605 ----------------------------------------------------------------------------------------------------
2021-07-27 13:50:57,605 Parameters:
2021-07-27 13:50:57,605  - learning_rate: "0.1"
2021-07-27 13:50:57,605  - mini_batch_size: "10"
2021-07-27 13:50:57,605  - patience: "5"
2021-07-27 13:50:57,605  - anneal_factor: "0.5"
2021-07-27 13:50:57,605  - max_epochs: "10"
2021-07-27 13:50:57,605  - shuffle: "True"
2021-07-27 13:50:57,605  - train_with_dev: "False"
2021-07-27 13:50:57,605  - batch_growth_annealing: "False"
2021-07-27 13:50:57,605 ----------------------------------------------------------------------------------------------------
2021-07-27 13:50:57,605 Model training base path: "model"
2021-07-27 13:50:57,605 ----------------------------------------------------------------------------------------------------
2021-07-27 13:50:57,605 Device: cpu
2021-07-27 13:50:57,605 ----------------------------------------------------------------------------------------------------
2021-07-27 13:50:57,605 Embeddings storage mode: cpu
2021-07-27 13:50:57,605 ----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/ADVANDS_Workspaces/Fiedler/test/mytest/flair/main.py", line 52, in <module>
    max_epochs=10)
  File "C:\ADVANDS_Workspaces\Fiedler\envs\ano\lib\site-packages\flair\trainers\trainer.py", line 381, in train
    loss = self.model.forward_loss(batch_step)
  File "C:\ADVANDS_Workspaces\Fiedler\envs\ano\lib\site-packages\flair\models\text_classification_model.py", line 144, in forward_loss
    scores = self.forward(data_points)
  File "C:\ADVANDS_Workspaces\Fiedler\envs\ano\lib\site-packages\flair\models\text_classification_model.py", line 97, in forward
    self.document_embeddings.embed(sentences)
  File "C:\ADVANDS_Workspaces\Fiedler\envs\ano\lib\site-packages\flair\embeddings\document.py", line 313, in embed
    word_embeddings = torch.cat(word_embeddings, dim=0).to(flair.device)
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPU, QuantizedCPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at aten\src\ATen\CPUType.cpp:2127 [kernel]
QuantizedCPU: registered at aten\src\ATen\QuantizedCPUType.cpp:297 [kernel]
BackendSelect: fallthrough registered at ..\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at ..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
AutogradOther: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:8078 [autograd kernel]
AutogradCPU: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:8078 [autograd kernel]
AutogradCUDA: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:8078 [autograd kernel]
AutogradXLA: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse1: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse2: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse3: registered at ..\torch\csrc\autograd\generated\VariableType_2.cpp:8078 [autograd kernel]
Tracer: registered at ..\torch\csrc\autograd\generated\TraceType_2.cpp:9654 [kernel]
Autocast: registered at ..\aten\src\ATen\autocast_mode.cpp:258 [kernel]
Batched: registered at ..\aten\src\ATen\BatchingRegistrations.cpp:511 [backend fallback]
VmapMode: fallthrough registered at ..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]
Process finished with exit code 1

**Code**
column_name_map = {4: "text", 3: "label_topic"}
corpus: Corpus = CSVClassificationCorpus(r"D:\Projekte\_Lieferungen\mails\flair_training",
                                         column_name_map,
                                         skip_header=True,
                                         delimiter=',',
                                         encoding='utf-8',
                                         doublequote=True
                                        )
label_dict = corpus.make_label_dictionary()
word_embedding = WordEmbeddings(r'D:\Transfer\flair\de-wiki-fasttext-300d-1M')
document_embeddings = DocumentPoolEmbeddings([word_embedding])
classifier = TextClassifier(document_embeddings, label_dictionary=label_dict)
trainer = ModelTrainer(classifier, corpus)
trainer.train('model',
              num_workers=0,
              learning_rate=0.1,
              mini_batch_size=10,
              anneal_factor=0.5,
              patience=5,
              max_epochs=10)

**Environment:**
OS: Microsoft Windows Server 2016, Version 1607 (OS Build 14393.4225)
flair==0.8.0.post1
toolz==0.9.0
torch==1.7.1+cu101
torchaudio==0.7.2
torchcontrib==0.0.2
torchvision==0.8.2+cu101

**Comment by LarsFied** [comment]
I got the solution. The corpus contained an empty Text. So the following line helped:
corpus.filter_empty_sentences()

However the error message was very confusing. I also found a DivisionByZero problem in trainer.py in the following line:
log.info(
                            f"epoch {self.epoch} - iter {seen_batches}/{total_number_of_batches} - loss "
                            f"{train_loss / seen_batches:.8f} - samples/sec: {mini_batch_size * modulo / **batch_time**:.2f}"
                            f" - lr: {learning_rate:.6f}{momentum_info}"
                        )

On my fast machine with a small text **batch_time** can be Zero.
