### ISSUE TITLE
How much CUDA memory is needed to train a new NER tagger?

### ISSUE THREAD

**Issue by rjgarciar** [flairNLP/flair#2364]
Hi, I'm trying to train a NER Portuguese tagger with this script:

```python
import torch
from multiprocessing import freeze_support
from flair.visual.training_curves import Plotter

if __name__ == '__main__':
	freeze_support()

	# 1. get the corpus
	from flair.datasets import WIKINER_PORTUGUESE

	corpus = WIKINER_PORTUGUESE()

	# 2. what tag do we want to predict?
	tag_type = 'ner'

	# 3. make the tag dictionary from the corpus
	tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)

	# 4. initialize fine-tuneable transformer embeddings WITH document context
	from flair.embeddings import TransformerWordEmbeddings

	embeddings = TransformerWordEmbeddings(
	    model='xlm-roberta-large',
	    layers="-1",
	    subtoken_pooling="first",
	    fine_tune=True,
	    use_context=True,
	)

	# 5. initialize bare-bones sequence tagger (no CRF, no RNN, no reprojection)
	from flair.models import SequenceTagger

	tagger = SequenceTagger(
	    hidden_size=256,
	    embeddings=embeddings,
	    tag_dictionary=tag_dictionary,
	    tag_type='ner',
	    use_crf=False,
	    use_rnn=False,
	    reproject_embeddings=False,
	)

	# 6. initialize trainer with AdamW optimizer
	from flair.trainers import ModelTrainer

	trainer = ModelTrainer(tagger, corpus, optimizer=torch.optim.AdamW)

	# 7. run training with XLM parameters (20 epochs, small LR)
	from torch.optim.lr_scheduler import OneCycleLR

	trainer.train(R'C:\Users\ramon\.flair\models\ner-portuguese2',
	              learning_rate=5.0e-6,
	              mini_batch_size=4,
	              mini_batch_chunk_size=1,
	              max_epochs=20,
	              scheduler=OneCycleLR,
	              embeddings_storage_mode='none',
	              weight_decay=0.,
	              )

	plotter = Plotter()
	plotter.plot_training_curves("resources/taggers/example-ner/loss.tsv")
	plotter.plot_weights("resources/taggers/example-ner/weights.txt")
```

but I always get this error:

> Traceback (most recent call last):
>   File "train-flair2.py", line 51, in <module> trainer.train(R'C:\Users\ramon\.flair\models\ner-portuguese',
>   File "C:\Users\Protecmedia\.conda\envs\pyt\lib\site-packages\flair\trainers\trainer.py", line 388, in train loss.backward()
>   File "C:\Users\Protecmedia\.conda\envs\pyt\lib\site-packages\torch\tensor.py", line 221, in backward torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "C:\Users\Protecmedia\.conda\envs\pyt\lib\site-packages\torch\autograd\__init__.py", line 130, in backward Variable._execution_engine.run_backward(
> RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 4.00 GiB total capacity; 3.08 GiB already allocated; 0 bytes free; 3.14 GiB reserved in total by PyTorch)

**ENVIRONMENT**

```
NVIDA GeForce GTX 1050 Ti (4Gb)

     active environment : pyt
    active env location : C:\Users\Protecmedia\.conda\envs\pyt
            shell level : 1
       user config file : C:\Users\ramon\.condarc
 populated config files : C:\Users\ramon\.condarc
          conda version : 4.8.3
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __cuda=11.4
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\ramon\.conda\pkgs
                          C:\Users\ramon\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Protecmedia\.conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\ramon\.conda\envs
                          C:\Users\ramon\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.26.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False
```

Is this CUDA enough? Do I have to purchase a better one? Is there a way to limit CUDA memory usage?

Thanks
Ramón García

**Comment by philfuchs** [comment]
I have a similar problem when using stacked embeddings. Could you set `embeddings_storage_mode='cpu'` in your `trainer.train` method and see if it works, i.e. how much RAM the embeddings take up? Also, #2157 might help give an intuition of vram requirement.

**Comment by alanakbik** [comment]
@rjgarciar yes unfortunately 4 GB is not enough to fine-tune an XLM-RoBERTa-large model, especially if you set use_context=True which gives best results. You could try a smaller model like a standard BERT or try to get access to a GPU with more memory.

**Comment by magistermilitum** [comment]
You must try with at least 11GB card for a BERT model. So, maybe a RTX 2080ti. Trasformers are high consuming vram memory and needs lots of cores also. New 3000 nvidia generation, for example 3080ti with 11GB can be perfect or T100, V100 with 16GB which you can get from colab pro for an afordable price.

**Comment by alanakbik** [comment]
Closing, but feel free to reopen if you have more questions!
