### ISSUE TITLE
Tokenization mismatch and RuntimeError (invalid shape)

### ISSUE THREAD

**Issue by philfuchs** [flairNLP/flair#2390]
**Describe the bug**
I'm embedding text using `TransformerWordEmbeddings('bert-base-german-cased')` and performing NER using a `SequenceTagger` without rnn and crf afterwards. The embeddings seem to fail when encountering certain unicode symbols.

**To Reproduce**
I used the tutorials in this repository for named entity recognition, so it's very simple code. The data, however, is proprietary so I cannot provide samples besides the one in the error message.

```
    embeddings = TransformerWordEmbeddings('bert-base-german-cased')
    tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type,
                                        use_rnn=False,
                                        use_crf=False)
```

**Error:**
```
2021-08-23 10:20:57,775 Device: cuda:0
2021-08-23 10:20:57,775 ----------------------------------------------------------------------------------------------------
2021-08-23 10:20:57,775 Embeddings storage mode: cpu
2021-08-23 10:20:57,776 ----------------------------------------------------------------------------------------------------
2021-08-23 10:21:18,137 epoch 1 - iter 34/340 - loss 0.78756023 - samples/sec: 53.44 - lr: 0.100000
2021-08-23 10:21:38,630 epoch 1 - iter 68/340 - loss 0.68339882 - samples/sec: 53.35 - lr: 0.100000
2021-08-23 10:21:58,865 epoch 1 - iter 102/340 - loss 0.65048363 - samples/sec: 53.98 - lr: 0.100000
2021-08-23 10:22:19,286 epoch 1 - iter 136/340 - loss 0.61642147 - samples/sec: 53.49 - lr: 0.100000
2021-08-23 10:22:40,070 epoch 1 - iter 170/340 - loss 0.59570234 - samples/sec: 52.55 - lr: 0.100000
2021-08-23 10:22:58,696 Tokenization MISMATCH in sentence '[REDACTED] C / C++ Python ETL Tools Informatica Pentaho DI Big Data / Frameworks  Microsoft Azure  Apache Avro       '
2021-08-23 10:22:58,696 Last matched: 'Token: 43 '
2021-08-23 10:22:58,696 Last sentence: 'Token: 49 '
2021-08-23 10:22:58,696 subtokenized: '[[REDACTED] 'C', '/', 'C', '+', '+', 'Py', '##th', '##on', 'E', '##TL', 'To', '##ols', 'Inform', '##ati', '##ca', 'Pent', '##ah', '##o', 'D', '##I', 'Big', 'Dat', '##a', '/', 'Fra', '##me', '##work', '##s', 'Microsoft', 'Az', '##ure', 'Ap', '##ache', 'Av', '##ro']'
Traceback (most recent call last):
  File "train_transformer.py", line 56, in <module>
    trainer.train(path,
  File "/home/phil.fuchs/anaconda3/envs/flairtest/lib/python3.8/site-packages/flair/trainers/trainer.py", line 381, in train
    loss = self.model.forward_loss(batch_step)
  File "/home/phil.fuchs/anaconda3/envs/flairtest/lib/python3.8/site-packages/flair/models/sequence_tagger_model.py", line 637, in forward_loss
    features = self.forward(data_points)
  File "/home/phil.fuchs/anaconda3/envs/flairtest/lib/python3.8/site-packages/flair/models/sequence_tagger_model.py", line 668, in forward
    sentence_tensor = torch.cat(all_embs).view(
RuntimeError: shape '[32, 109, 768]' is invalid for input of size 2673408
```

![image](https://user-images.githubusercontent.com/88037858/130417435-0ab1cd63-1ebc-4266-9e26-3c85f6800f8b.png)

```
julia> ''
'\uf06c': Unicode U+F06C (category Co: Other, private use)
```

This seems to trip up the subword tokeniser. Is this behaviour expected for characters like these and I need to filter, or does this issue persist in the current version? This could very well be a case of "you're holding it wrong". :smile: 

Similar issues: 
- https://github.com/flairNLP/flair/issues/1699
- https://github.com/flairNLP/flair/issues?q=is%3Aissue+tokenization+mismatch

**Environment:**
 - OS: Ubuntu 20.04
 - Version: flair==0.8.0.post1

**Comment by philfuchs** [comment]
I have discarded any non-ascii characters from my data set and now I can use the transformer embeddings (at least with the data points I have used so far...).

**Comment by alanakbik** [comment]
@philfuchs could you share a small file with one or two sentences that cause this error? That would help us debug.

**Comment by philfuchs** [comment]
I can't share any data due to privacy concerns but I will see if I can recreate the error with different data.

**Comment by philfuchs** [comment]
@alanakbik Strangely enough, the error does not occur by pasting the characters into a CoNLL sample set; the code hasn't changed. I'll close the issue until I can somehow reproduce it, since it seems to work for now.
