### ISSUE TITLE
How do you train a language model on a corpus?

### ISSUE THREAD

**Issue by yrahul3910** [flairNLP/flair#2461]
I have a large text corpus, and I would like to train, say, a `bert-base-uncased` `TransformerDocumentEmbeddings` model in an unsupervised manner (i.e., I want better word/document embeddings for my data). How do I do that using FLAIR? The `LanguageModelTrainer` class does not do it, since it requires a `init_weights` function.

**Comment by yrahul3910** [comment]
I made some progress! For reference, here's my updated code:

```py
import sys
from pathlib import Path
from flair.data import Dictionary
from flair.trainers import ModelTrainer
from flair.trainers.language_model_trainer import TextCorpus
from flair.embeddings import TransformerWordEmbeddings


if len(sys.argv) < 2:
	print('Usage:', sys.argv[0], 'PATH_TO_TRAIN_FILE')
	sys.exit(1)

is_forward_lm = True
dictionary = Dictionary.load('chars')
model = TransformerWordEmbeddings('bert-base-uncased', fine_tune=True)
corpus = TextCorpus(sys.argv[1], dictionary, is_forward_lm, character_level=True)

trainer = ModelTrainer(model, corpus)
trainer.train('./models/bert-base-uncased/', mini_batch_size=2, sequence_length=250)
```

In doing so, I get the following error:
```
2021-10-03 00:12:40,545 ----------------------------------------------------------------------------------------------------
2021-10-03 00:12:40,545 Model training base path: "models/bert-base-uncased"
2021-10-03 00:12:40,545 ----------------------------------------------------------------------------------------------------
2021-10-03 00:12:40,546 Device: cuda:0
2021-10-03 00:12:40,546 ----------------------------------------------------------------------------------------------------
2021-10-03 00:12:40,546 Embeddings storage mode: cpu
Traceback (most recent call last):
  File "train_lm.py", line 19, in <module>
    trainer.train('./models/bert-base-uncased/', mini_batch_size=2, sequence_length=250)
  File "/home/ryedida/.local/lib/python3.6/site-packages/flair/trainers/trainer.py", line 198, in train
    if (not param_selection_mode and self.corpus.test and monitor_test)
RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```

**Comment by alanakbik** [comment]
Hello @yrahul3910 in Flair you can only fine-tune existing transformer-based language models, like in the tutorial [here](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#training-a-named-entity-recognition-ner-model-with-transformers) or [here](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#training-a-text-classification-model). 

If you want to train a new transformer language model from scratch you should use the huggingface library instead.
