### ISSUE TITLE
Error with PyTorch 1.10

### ISSUE THREAD

**Issue by AdirRahamim** [flairNLP/flair#2520]
Hi,

I'm working with PyTorch version 1.10, flair version 0.9, and allenNLP version2.8, However, when I try to import Elmo model and initialize it using the following code:
'from flair.embeddings import ELMoEmbeddings
embedding = ELMoEmbeddings()`
It arises the following error:
Traceback (most recent call last):
  File "/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-378cb53b2e8d>", line 1, in <module>
    embedding = ELMoEmbeddings()
  File "/lib/python3.8/site-packages/flair/embeddings/token.py", line 1834, in __init__
    import allennlp.commands.elmo
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/lib/python3.8/site-packages/allennlp/commands/__init__.py", line 9, in <module>
    from allennlp.commands.build_vocab import BuildVocab
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/lib/python3.8/site-packages/allennlp/commands/build_vocab.py", line 17, in <module>
    from allennlp.training.util import make_vocab_from_params
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/python3.8/site-packages/allennlp/training/__init__.py", line 2, in <module>
    from allennlp.training.no_op_trainer import NoOpTrainer
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/lib/python3.8/site-packages/allennlp/training/no_op_trainer.py", line 6, in <module>
    from allennlp.models import Model
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/lib/python3.8/site-packages/allennlp/models/__init__.py", line 6, in <module>
    from allennlp.models.model import Model
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/lib/python3.8/site-packages/allennlp/models/model.py", line 22, in <module>
    from allennlp.nn.parallel import DdpAccelerator
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/lib/python3.8/site-packages/allennlp/nn/parallel/__init__.py", line 7, in <module>
    from allennlp.nn.parallel.fairscale_fsdp_accelerator import (
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/lib/python3.8/site-packages/allennlp/nn/parallel/fairscale_fsdp_accelerator.py", line 4, in <module>
    from fairscale.nn import FullyShardedDataParallel as FS_FSDP
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/lib/python3.8/site-packages/fairscale/__init__.py", line 15, in <module>
    from . import nn
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/lib/python3.8/site-packages/fairscale/nn/__init__.py", line 9, in <module>
    from .data_parallel import FullyShardedDataParallel, ShardedDataParallel
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/lib/python3.8/site-packages/fairscale/nn/data_parallel/__init__.py", line 8, in <module>
    from .fully_sharded_data_parallel import FullyShardedDataParallel, TrainingState, auto_wrap_bn
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/lib/python3.8/site-packages/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 34, in <module>
    from torch.distributed import ProcessGroup
ImportError: cannot import name 'ProcessGroup' from 'torch.distributed' (/lib/python3.8/site-packages/torch/distributed/__init__.py)

**Comment by sadakmed** [comment]
that because flair relies on allenNLP==0.9
