### ISSUE TITLE
AttributeError: 'str' object has no attribute 'tokens'

### ISSUE THREAD

**Issue by Ketki-Savle** [flairNLP/flair#2562]
Hello, 

Specs:

Flair=0.10
Transformers = 4.13
Torch = 1.10

I have fine-tuned clinicalBERT model for NER using i2b2 data in CoNLL format. Now when I am trying to predict entities using the 'best-model.pt' file, i am getting an error : AttributeError: 'str' object has no attribute 'tokens'

This is occurring on 
tagger.predict(sentences) 
line. 

We are predicting entities using simple txt file. It is one file with 124 sentences. Happy to share my code if needed. Could you please help. Thanks. 

Full trace:

2021-12-17 03:44:40,882 loading file ./output_all_entity/best-model.pt
Starting to predict on  corpus.txt
Number of sentences:  124
Traceback (most recent call last):
  File "auth_ner_predict.py", line 102, in <module>
    labeler.process_files(subdir, os.path.join(out_dir, subdir_dir))
  File "auth_ner_predict.py", line 54, in process_files
    predictions = self.predict(file_sentences)
  File "auth_ner_predict.py", line 20, in predict
    sentence_results = self.tagger.predict(sentences)
  File "/home/jovyan/envs/nlp1/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 357, in predict
    batch = self._filter_empty_sentences(batch)
  File "/home/jovyan/envs/nlp1/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 747, in _filter_empty_sentences
    filtered_sentences = [sentence for sentence in sentences if sentence.tokens]
  File "/home/jovyan/envs/nlp1/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 747, in <listcomp>
    filtered_sentences = [sentence for sentence in sentences if sentence.tokens]
AttributeError: 'str' object has no attribute 'tokens'

**Comment by whoisjones** [comment]
hi @Ketki-Savle, have you transformed your data into a flair corpus before passing it to the predict method?

**Comment by Ketki-Savle** [comment]
Yes, I have. Thank you.

**Comment by Ketki-Savle** [comment]
Alright! I found a way to solve this error! 

I was missing one step while predicting and that is not passing my strings through "Sentence" object imported from flair. 
Once I add that, it works just fine. Thank you for your support. Closing this issue.

**Comment by Frenks7** [comment]
Hi, I have a similar problem, can you help me understand how to solve it? This is the program in python:

import pygame 
import pgzrun 
from os import listdir
from random import sample
WIDTH = 12800 
HEIGHT = 7200
caselle = []
for n in range(7):
    casella = Actor('neutra')
    casella.pos = 602, 512-n*58
    casella.append(casella)
def draw():
    screen.surface = pygame.display.set_mode(
        (WIDTH, HEIGHT), pygame.FULLSCREEN) 
    for casella in caselle:
         casella.draw()
pgzrun.go()

But the terminal gives me this error message:
[Running] python -u "c:\Users\Administrator\Desktop\PytoProgram\PYSarabanda\sarabanda.py"
pygame 2.5.1 (SDL 2.28.2, Python 3.11.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\PytoProgram\PYSarabanda\sarabanda.py", line 28, in <module>
    casella = Actor('neutra')
              ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\apify\actor.py", line 121, in __init__
    self._apify_client = self.new_client()
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\apify\_utils.py", line 298, in wrapper
    return implementation(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\apify\actor.py", line 488, in _new_client_internal
    token = token or self._config.token
                     ^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'token'
[Done] exited with code=1 in 3.672 seconds

What does it mean and how can I solve it?
