### ISSUE TITLE
AttributeError: 'TransformerDocumentEmbeddings' object has no attribute 'init_hidden'

### ISSUE THREAD

**Issue by yrahul3910** [flairNLP/flair#2631]
**Describe the bug**
I am trying to fine-tune a language model, and my log is as follows:

```
ryedida@deeplearning-9-vm:~/src$ python3 train_lm.py
2022-02-13 06:13:58,163 read text file with 17612887 lines
2022-02-13 06:27:08,040 read text file with 8800340 lines
2022-02-13 06:33:19,149 read text file with 83656 lines
2022-02-13 06:33:19,160 read text file with 83382 lines
2022-02-13 06:33:19,203 shuffled
2022-02-13 06:33:19,214 shuffled
2022-02-13 06:33:22,574 Sequence length is 100
2022-02-13 06:33:22,653 Split 1	 - (06:33:22)
2022-02-13 06:33:23,049 read text file with 83519 lines
2022-02-13 06:33:23,076 read text file with 83821 lines
2022-02-13 06:33:23,105 shuffled
2022-02-13 06:33:23,131 shuffled
Traceback (most recent call last):
  File "train_lm.py", line 13, in <module>
    trainer.train('../models/', sequence_length=100, mini_batch_size=2)
  File "/opt/conda/lib/python3.7/site-packages/flair/trainers/language_model_trainer.py", line 293, in train
    hidden = self.model.init_hidden(mini_batch_size)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'TransformerDocumentEmbeddings' object has no attribute 'init_hidden'
```

**To Reproduce**

My code in `train_lm.py` is:

```
from flair.embeddings import TransformerDocumentEmbeddings
from flair.data import Dictionary
from flair.trainers.language_model_trainer import LanguageModelTrainer, TextCorpus


model = TransformerDocumentEmbeddings('bert-base-uncased',
                                  fine_tune=True)
dictionary = Dictionary.load('chars')
corpus = TextCorpus('../data/',
                    dictionary)

trainer = LanguageModelTrainer(model, corpus)
trainer.train('../models/', sequence_length=100, mini_batch_size=2)
```

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: Debian
 - Version [e.g. flair-0.3.2]: flair-0.10

How do I solve this?

**Comment by hsoaso** [comment]
Yeah, experiencing the same problem, please follow up
