### ISSUE TITLE
CUDA oom with embeddings_storage_mode="cpu"

### ISSUE THREAD

**Issue by philipp-kohl** [flairNLP/flair#2663]
**Describe the bug**
Hi everyone,
I try to train a classification model with flair. Due to long documents I wanted to store the embeddings in RAM. Hence, I set embeddings_storage_mode="cpu". But I faced the issue that my GPU memory is allocated linearly until no more memory is available (48GB). Setting embeddings_storage_mode="none" fixed the issue for me. I understand the documentation in the way that in every batch the embeddings will be transferred to the mentioned device. But it seems that this is not happening in this case. The computation fails in the first epoch. Surprisingly (for me) this can also be fixed with a higher batch size.

FYI: My corpus is not that big: ~ 3000 documents.

```
2022-03-09 12:38:06,332 ----------------------------------------------------------------------------------------------------
2022-03-09 12:38:06,332 Corpus: "Corpus: 2131 train + 457 dev + 456 test sentences"
2022-03-09 12:38:06,332 ----------------------------------------------------------------------------------------------------
2022-03-09 12:38:06,333 Parameters:
2022-03-09 12:38:06,333  - learning_rate: "0.003"
2022-03-09 12:38:06,333  - mini_batch_size: "1"
2022-03-09 12:38:06,333  - patience: "2"
2022-03-09 12:38:06,333  - anneal_factor: "0.5"
2022-03-09 12:38:06,333  - max_epochs: "400"
2022-03-09 12:38:06,333  - shuffle: "True"
2022-03-09 12:38:06,333  - train_with_dev: "False"
2022-03-09 12:38:06,333  - batch_growth_annealing: "False"
2022-03-09 12:38:06,333 ----------------------------------------------------------------------------------------------------
2022-03-09 12:38:06,333 Model training base path: "models/textcat_flair_trf/model"
2022-03-09 12:38:06,333 ----------------------------------------------------------------------------------------------------
2022-03-09 12:38:06,333 Device: cuda:0
2022-03-09 12:38:06,333 ----------------------------------------------------------------------------------------------------
2022-03-09 12:38:06,333 Embeddings storage mode: cpu
2022-03-09 12:38:06,336 ----------------------------------------------------------------------------------------------------
2022-03-09 12:38:16,887 epoch 1 - iter 213/2131 - loss 0.18355409 - samples/sec: 20.20 - lr: 0.003000                                
2022-03-09 12:38:27,849 epoch 1 - iter 426/2131 - loss 0.16106707 - samples/sec: 19.45 - lr: 0.003000                                
2022-03-09 12:38:37,837 epoch 1 - iter 639/2131 - loss 0.14019156 - samples/sec: 21.34 - lr: 0.003000                                
2022-03-09 12:38:48,250 epoch 1 - iter 852/2131 - loss 0.13683440 - samples/sec: 20.47 - lr: 0.003000                                
2022-03-09 12:38:58,480 epoch 1 - iter 1065/2131 - loss 0.12751414 - samples/sec: 20.84 - lr: 0.003000                               
2022-03-09 12:39:08,909 epoch 1 - iter 1278/2131 - loss 0.12958945 - samples/sec: 20.44 - lr: 0.003000                               
2022-03-09 12:39:19,564 epoch 1 - iter 1491/2131 - loss 0.12343366 - samples/sec: 20.01 - lr: 0.003000                               
2022-03-09 12:39:30,485 epoch 1 - iter 1704/2131 - loss 0.11901164 - samples/sec: 19.52 - lr: 0.003000                               
2022-03-09 12:39:41,196 epoch 1 - iter 1917/2131 - loss 0.11457392 - samples/sec: 19.90 - lr: 0.003000
Traceback (most recent call last):                                                                                                      
  File "trainer.py", line 62, in <module>                                                                     
    cmd_train()                                                                                                                         
  File ".../lib/python3.8/site-packages/click/core.py", line 829, in __call__              
    return self.main(*args, **kwargs)                                                                                                   
  File ".../lib/python3.8/site-packages/click/core.py", line 782, in main                  
    rv = self.invoke(ctx)                                                                                                               
  File ".../lib/python3.8/site-packages/click/core.py", line 1066, in invoke               
    return ctx.invoke(self.callback, **ctx.params)                                                                                      
  File ".../lib/python3.8/site-packages/click/core.py", line 610, in invoke                
    return callback(*args, **kwargs)                                                                                                    
  File "./iorder4you/models/flair/trainer.py", line 45, in cmd_train                                                                    
    trainer.train(                                                                                                                      
  File ".../lib/python3.8/site-packages/flair/trainers/trainer.py", line 467, in train     
    loss = self.model.forward_loss(batch_step)                                                                                          
  File ".../lib/python3.8/site-packages/flair/nn/model.py", line 489, in forward_loss      
    scores, labels = self.forward_pass(sentences)                                                                                       
  File ".../lib/python3.8/site-packages/flair/models/text_classification_model.py", line 60
, in forward_pass                                                                                                                       
    self.document_embeddings.embed(sentences)                                                                                           
  File ".../lib/python3.8/site-packages/flair/embeddings/base.py", line 60, in embed       
    self._add_embeddings_internal(sentences)                                                                                            
  File ".../lib/python3.8/site-packages/flair/embeddings/document.py", line 158, in _add_em
beddings_internal                                                                                                                       
    else self.model(input_ids)[-1]                                                                                                      
  File ".../lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl 
    return forward_call(*input, **kwargs)                                                                                               
  File ".../lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 99
6, in forward                                                                                                                           
    encoder_outputs = self.encoder(                                                                                                     
  File ".../lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_im
pl                                                                                                                                      
    return forward_call(*input, **kwargs)                                                                                               
  File ".../lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 58
5, in forward                                                                                                                           
    layer_outputs = layer_module(                                                                                                       
  File ".../lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_im
pl                                                                                                                                      
    return forward_call(*input, **kwargs)                                                                                               
  File ".../lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 47
2, in forward                                                                                                                           
    self_attention_outputs = self.attention(                                                                                            
  File ".../lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_im
pl                                                                                                                                      
    return forward_call(*input, **kwargs)                                                                                               
  File ".../lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 40
2, in forward                                                                                                                           
    self_outputs = self.self(                                                                                                           
  File ".../lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_im
pl                                                                                                                                      
    return forward_call(*input, **kwargs)                                                                                               
  File ".../lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 34
2, in forward                                                                                                                           
    context_layer = context_layer.permute(0, 2, 1, 3).contiguous()                                                                      
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 47.54 GiB total capacity; 45.49 GiB already allocated; 7.25 MiB fr
ee; 45.50 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentati
on.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**To Reproduce**
My corpus is not public. 
```
# 1. get the corpus
    corpus: Corpus = JsonlCorpus(train_path, "train.jsonl", "test.jsonl", "dev.jsonl") # https://github.com/flairNLP/flair/pull/2653

    # 2. what label do we want to predict?
    label_type = "category"

    # 3. create the label dictionary
    label_dict = corpus.make_label_dictionary(label_type=label_type)

    # 4. initialize transformer document embeddings (many models are available)
    document_embeddings = TransformerDocumentEmbeddings("deepset/gbert-base", fine_tune=True)

    # 5. create the text classifier
    classifier = TextClassifier(
        document_embeddings, multi_label=True, label_dictionary=label_dict, label_type=label_type
    )

    # 6. initialize trainer
    trainer = ModelTrainer(classifier, corpus)

    # 7. run training with fine-tuning
    trainer.train(
        model_path,
        learning_rate=0.003,
        mini_batch_size=1,
        max_epochs=400,
        min_learning_rate=1e-7,
        #optimizer=AdamW,
        patience=2,
        main_evaluation_metric=("macro avg", "f1-score"),
        embeddings_storage_mode="cpu",
    )
```

**Expected behavior**
Not allocating more and more GPU memory, due to transferring the embeddings to RAM.

**Environment (please complete the following information):**
 - Linux:
 - flair:0.10:

**Comment by alanakbik** [comment]
Hello @philipp-kohl if you use fine-tuneable embeddings no embeddings will be stored in either case (fine-tuning means they will alwys change so storing them makes no sense). So the embeddings_storage_mode should have no effect here. 

It is quite strange that a larger mini-batch size somehow fixes this issue, this should not happen.
