### ISSUE TITLE
Iterating over the cuda-devices fails with a Type-Error 

### ISSUE THREAD

**Issue by Weyaaron** [flairNLP/flair#2751]
**Describe the bug**
While iterating over the cuda-devices, flair fails to load the device properly.  This method of iteration is analogous to the method described in this issue: https://github.com/flairNLP/flair/issues/464

**To Reproduce**
```
import flair
import torch

for i in range(0,torch.cuda.device_count()):
    current_device = torch.cuda.device(i)
    print(current_device)
    flair.device = torch.cuda.device(i)

# Actually use flair, this is cut from the example for brevity 
```
**Expected behavior**
That the code snipped changes the flair device properly. Instead, the programm crashes with the following error:

```
<torch.cuda.device object at 0x7f8fd0eee880>
2022-05-07 09:24:41,338 loading file /vol/fob-vol4/mi17/weyaaron/.flair/models/ner-german-large/6b8de9edd73722050be2547acf64c037b2df833c6e8f0e88934de08385e26c1e.4b0797effcc6ebb1889d5d29784b97f0a099c1569b319d87d7c387e44e2bba48
Traceback (most recent call last):
  File "/vol/fob-vol4/mi17/weyaaron/Zitatsuchmaschine/main.py", line 54, in <module>
    main()
  File "/vol/fob-vol4/mi17/weyaaron/Zitatsuchmaschine/main.py", line 50, in main
    active_mode.execute_full_cycle()
  File "/vol/fob-vol4/mi17/weyaaron/Zitatsuchmaschine/src/modes/nlp_mode.py", line 14, in execute_full_cycle
    self.setup()
  File "/vol/fob-vol4/mi17/weyaaron/Zitatsuchmaschine/src/modes/impl/extraction_mode.py", line 14, in setup
    self.quote_extractor = QuoteExtractor(
  File "<string>", line 16, in __init__
  File "/vol/fob-vol4/mi17/weyaaron/Zitatsuchmaschine/src/nlp/quote_extraction/quote_extraction.py", line 94, in __post_init__
    self.__tagger = MultiTagger.load([self.__ner_model, self.__quote_model, self.__quotee_model])
  File "/glusterfs/dfs-gfs-dist/qse-common/miniconda-common/envs/qse-dev-system/lib/python3.9/site-packages/flair/models/sequence_tagger_model.py", line 1330, in load
    model = SequenceTagger.load(model_name)
  File "/glusterfs/dfs-gfs-dist/qse-common/miniconda-common/envs/qse-dev-system/lib/python3.9/site-packages/flair/nn.py", line 88, in load
    state = torch.load(f, map_location='cpu')
  File "/glusterfs/dfs-gfs-dist/qse-common/miniconda-common/envs/qse-dev-system/lib/python3.9/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/glusterfs/dfs-gfs-dist/qse-common/miniconda-common/envs/qse-dev-system/lib/python3.9/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/glusterfs/dfs-gfs-dist/qse-common/miniconda-common/envs/qse-dev-system/lib/python3.9/site-packages/flair/embeddings/token.py", line 1284, in __setstate__
    embedding = TransformerWordEmbeddings(
  File "/glusterfs/dfs-gfs-dist/qse-common/miniconda-common/envs/qse-dev-system/lib/python3.9/site-packages/flair/embeddings/token.py", line 856, in __init__
    self.model.to(flair.device)
  File "/glusterfs/dfs-gfs-dist/qse-common/miniconda-common/envs/qse-dev-system/lib/python3.9/site-packages/torch/nn/modules/module.py", line 880, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
TypeError: to() received an invalid combination of arguments - got (device), but expected one of:
 * (torch.device device, torch.dtype dtype, bool non_blocking, bool copy, *, torch.memory_format memory_format)
 * (torch.dtype dtype, bool non_blocking, bool copy, *, torch.memory_format memory_format)
 * (Tensor tensor, bool non_blocking, bool copy, *, torch.memory_format memory_format)
```

**Environment (please complete the following information):**
 - Linux
 - Version 0.8.0.post1

**Additional context**
This is my naive attempt at iterating over all cuda devices. If there is another approach, let me know.

**Comment by dobbersc** [comment]
I can't reproduce the error with the code above. But the error does occur when loading a model. It always helps provide a minimal example to reproduce the error. Is this what you are doing?

```python
import flair
import torch

from flair.models import SequenceTagger

flair.device = torch.cuda.device(0)
SequenceTagger.load('ner')  # Exception
```

Here you are using `torch.cuda.device`. According to the [documentation](https://pytorch.org/docs/stable/generated/torch.cuda.device.html#torch.cuda.device), this function is actually a context manager. What you properly want is [`torch.device`](https://pytorch.org/docs/stable/generated/torch.cuda.device.html).

To change flair's device use:

```python
import torch
import flair

flair.device = torch.device(0)  # cuda:0
```

**Comment by Weyaaron** [comment]
This looks promising, I will check it out tomorrow and report back.

**Comment by Weyaaron** [comment]
This is the solution I was looking for, I appreciate the quick help :)
