### ISSUE TITLE
requirements.txt missing from PyPI source tarball

### ISSUE THREAD

**Issue by boegel** [flairNLP/flair#2759]
**Describe the bug**

`requirements.txt` is missing from the source tarball that is available via PyPI (https://pypi.org/project/flair/0.11.2/#files).

That's a problem because `requirements.txt` is required by `setup.py`, see https://github.com/flairNLP/flair/blob/7491f4b4f3aa6e6c2832ddb67adb1243cbc15488/setup.py#L3-L4

**To Reproduce**

Download source tarball from PyPI, unpack it, try installing it with `pip install .`

**Expected behavior**

Installing with `pip install .` using source tarball from PyPI works.

**Screenshots**
*(not relevant)*

**Environment (please complete the following information):**
 - OS: Linux
 - Version: flair 0.11.2

**Additional context**

Error message produced by `pip install .`:

```
    Traceback (most recent call last):
      File "/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
        main()
      File "/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/setuptools/build_meta.py", line 258, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 3, in <module>
        with open("requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    Preparing wheel metadata: finished with status 'error'
```

**Comment by alanakbik** [comment]
@boegel thanks for reporting this! Do you happen to know what must be done in order for the `requirements.txt` to become part of the tarball?

**Comment by boegel** [comment]
As far as I know this problem still stands, so it should not be closed? cc @alanakbik

**Comment by boegel** [comment]
Don't close please, but fix the issue
