### ISSUE TITLE
NER training problem with BILOU format

### ISSUE THREAD

**Issue by sagorbrur** [flairNLP/flair#2774]
Hello,
Thank you so much for this beautiful tool.
My Flair version is 0.11.2
I am doing NER with `BILOU` format datasets. I am using `ColumnCorpus` option to feed my custom data,  But training stops and shows this error.
```
Traceback (most recent call last):
  File "train_ner.py", line 65, in <module>
    train(
  File "train_ner.py", line 57, in train
    trainer.train(log_dir,
  File "/home/sagor/anaconda3/envs/flair/lib/python3.8/site-packages/flair/trainers/trainer.py", line 502, in train
    loss = self.model.forward_loss(batch_step)
  File "/home/sagor/anaconda3/envs/flair/lib/python3.8/site-packages/flair/models/sequence_tagger_model.py", line 272, in forward_loss
    scores, gold_labels = self.forward(sentences)  # type: ignore
  File "/home/sagor/anaconda3/envs/flair/lib/python3.8/site-packages/flair/models/sequence_tagger_model.py", line 330, in forward
    gold_labels = self._get_gold_labels(sentences)
  File "/home/sagor/anaconda3/envs/flair/lib/python3.8/site-packages/flair/models/sequence_tagger_model.py", line 415, in _get_gold_labels
    if len(span) == 1:
TypeError: object of type 'Token' has no len()
```

Then I debugged thoroughly and modified the following line shown here in snippets.
If I add `U-` in the code, it's training perfectly, otherwise, it fails.
The working list is `["B-", "I-", "E-", "S-", "U-", "L-"]`
Does `Flair` support the `BILOU` format? Please let me know.
Also please let me know if this is a mergeable pull request if I create one with this issue solving.
Thanks and regards
https://github.com/flairNLP/flair/blob/88f332ab7b5ff89cfb02641c529fac286be08c15/flair/datasets/sequence_labeling.py#L614

**Comment by sagorbrur** [comment]
I found this a duplicate of #2016 , That's why I am closing this issue. sorry for this duplicate issue.
regards
