### ISSUE TITLE
TypeError: object of type 'Token' has no len()

### ISSUE THREAD

**Issue by Ihebzayen** [flairNLP/flair#2826]
2022-06-20 09:29:33,975 Reading data from input_data
2022-06-20 09:29:33,975 Train: input_data/train.txt
2022-06-20 09:29:33,975 Dev: input_data/valid.txt
2022-06-20 09:29:33,975 Test: input_data/test.txt
2022-06-20 09:29:45,152 Computing label dictionary. Progress:
14987it [00:00, 20715.78it/s]
2022-06-20 09:29:45,877 Dictionary created for label 'ner' with 21 values: I-NP (seen 66645 times), B-NP (seen 57387 times), B-PP (seen 18843 times), B-VP (seen 18047 times), I-VP (seen 8818 times), B-ADVP (seen 2637 times), B-SBAR (seen 1269 times), B-ADJP (seen 1165 times), -X- (seen 946 times), B-PRT (seen 527 times), I-ADJP (seen 211 times), I-ADVP (seen 138 times), I-PP (seen 103 times), B-INTJ (seen 59 times), I-CONJP (seen 39 times), B-LST (seen 32 times), B-CONJP (seen 31 times), I-SBAR (seen 19 times), I-LST (seen 4 times), I-INTJ (seen 1 times)
2022-06-20 09:29:47,038 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim.vectors.npy not found in cache, downloading to /tmp/tmpoa5zhn91
100% 160000128/160000128 [00:18<00:00, 8862868.93B/s]
2022-06-20 09:30:05,919 copying /tmp/tmpoa5zhn91 to cache at /root/.flair/embeddings/glove.gensim.vectors.npy
2022-06-20 09:30:06,267 removing temp file /tmp/tmpoa5zhn91
2022-06-20 09:30:07,115 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim not found in cache, downloading to /tmp/tmp0niqrwy0
100% 21494764/21494764 [00:04<00:00, 5228142.84B/s]

2022-06-20 09:30:12,086 copying /tmp/tmp0niqrwy0 to cache at /root/.flair/embeddings/glove.gensim
2022-06-20 09:30:12,112 removing temp file /tmp/tmp0niqrwy0
2022-06-20 09:30:16,237 https://flair.informatik.hu-berlin.de/resources/embeddings/flair/news-forward-0.4.1.pt not found in cache, downloading to /tmp/tmprrm89brb
100% 73034624/73034624 [00:08<00:00, 8139073.33B/s] 
2022-06-20 09:30:26,037 copying /tmp/tmprrm89brb to cache at /root/.flair/embeddings/news-forward-0.4.1.pt
2022-06-20 09:30:26,150 removing temp file /tmp/tmprrm89brb
2022-06-20 09:30:27,858 https://flair.informatik.hu-berlin.de/resources/embeddings/flair/news-backward-0.4.1.pt not found in cache, downloading to /tmp/tmpil1w_c93
100% 73034575/73034575 [00:08<00:00, 8283917.66B/s] 
2022-06-20 09:30:37,530 copying /tmp/tmpil1w_c93 to cache at /root/.flair/embeddings/news-backward-0.4.1.pt
2022-06-20 09:30:37,663 removing temp file /tmp/tmpil1w_c93
2022-06-20 09:30:37,940 SequenceTagger predicts: Dictionary with 21 tags: <unk>, I-NP, B-NP, B-PP, B-VP, I-VP, B-ADVP, B-SBAR, B-ADJP, -X-, B-PRT, I-ADJP, I-ADVP, I-PP, B-INTJ, I-CONJP, B-LST, B-CONJP, I-SBAR, I-LST, I-INTJ
2022-06-20 09:30:38,153 ----------------------------------------------------------------------------------------------------
2022-06-20 09:30:38,154 Model: "SequenceTagger(
  (embeddings): StackedEmbeddings(
    (list_embedding_0): WordEmbeddings(
      'glove'
      (embedding): Embedding(400001, 100)
    )
    (list_embedding_1): FlairEmbeddings(
      (lm): LanguageModel(
        (drop): Dropout(p=0.05, inplace=False)
        (encoder): Embedding(300, 100)
        (rnn): LSTM(100, 2048)
        (decoder): Linear(in_features=2048, out_features=300, bias=True)
      )
    )
    (list_embedding_2): FlairEmbeddings(
      (lm): LanguageModel(
        (drop): Dropout(p=0.05, inplace=False)
        (encoder): Embedding(300, 100)
        (rnn): LSTM(100, 2048)
        (decoder): Linear(in_features=2048, out_features=300, bias=True)
      )
    )
  )
  (word_dropout): WordDropout(p=0.05)
  (locked_dropout): LockedDropout(p=0.5)
  (embedding2nn): Linear(in_features=4196, out_features=4196, bias=True)
  (rnn): LSTM(4196, 256, batch_first=True, bidirectional=True)
  (linear): Linear(in_features=512, out_features=23, bias=True)
  (loss_function): ViterbiLoss()
  (crf): CRF()
)"
2022-06-20 09:30:38,154 ----------------------------------------------------------------------------------------------------
2022-06-20 09:30:38,154 Corpus: "Corpus: 14987 train + 3466 dev + 3684 test sentences"
2022-06-20 09:30:38,155 ----------------------------------------------------------------------------------------------------
2022-06-20 09:30:38,155 Parameters:
2022-06-20 09:30:38,155  - learning_rate: "0.010000"
2022-06-20 09:30:38,155  - mini_batch_size: "64"
2022-06-20 09:30:38,155  - patience: "3"
2022-06-20 09:30:38,156  - anneal_factor: "0.5"
2022-06-20 09:30:38,156  - max_epochs: "150"
2022-06-20 09:30:38,156  - shuffle: "True"
2022-06-20 09:30:38,156  - train_with_dev: "False"
2022-06-20 09:30:38,156  - batch_growth_annealing: "False"
2022-06-20 09:30:38,157 ----------------------------------------------------------------------------------------------------
2022-06-20 09:30:38,157 Model training base path: "output_folder"
2022-06-20 09:30:38,157 ----------------------------------------------------------------------------------------------------
2022-06-20 09:30:38,157 Device: cpu
2022-06-20 09:30:38,157 ----------------------------------------------------------------------------------------------------
2022-06-20 09:30:38,158 Embeddings storage mode: cpu
2022-06-20 09:30:38,158 ----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "flair_train.py", line 67, in <module>
    max_epochs=150)
  File "/usr/local/lib/python3.7/dist-packages/flair/trainers/trainer.py", line 500, in train
    loss = self.model.forward_loss(batch_step)
  File "/usr/local/lib/python3.7/dist-packages/flair/models/sequence_tagger_model.py", line 270, in forward_loss
    scores, gold_labels = self.forward(sentences)  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/flair/models/sequence_tagger_model.py", line 326, in forward
    gold_labels = self._get_gold_labels(sentences)
  File "/usr/local/lib/python3.7/dist-packages/flair/models/sequence_tagger_model.py", line 402, in _get_gold_labels
    if len(span) == 1:
TypeError: object of type 'Token' has no len()

hello guys, when i tried to train my model on conll2003 i faced this problem. can anyone help me.

**Comment by Lingepumpe** [comment]
This issue occurs when your train dataset is tagged on a token basis using BIO or BIOES tagging, and then you try to train a SequenceTagger on a predict_spans task...the sequencetagger incorrectly assumes he will have spans to work with in the training dataset.
Working on a fix.

**Comment by Ihebzayen** [comment]
thank you, i solved it

**Comment by Lingepumpe** [comment]
@mlentzen In flair-0.11.x, if you want to solve a span based problem with a SequenceTagger, make sure you label your dataset using the Span notation. Labeling individual tokens (using BIO or BIOES convention to signify spans) doesn't work and leads to the above error.

If your code now does:
```
sentence[0].add_label("ner", "B-Animal")
sentence[1].add_label("ner", "I-Animal")
```
...

Change it to:
`sentence[0:2].add_label("ner", "Animal")`

I am also working on a fix to make token labeling possible in this situtation again, but using span labeling is how you can fix it yourself quickly and probably easily.

**Comment by mlentzen** [comment]
Thank you very much! That is a quick and easy solution.

**Comment by pietrolesci** [comment]
Hi there,

Having the same issues. I am using the `JsonlCorpus` to load data and the construction of `Sentence`s is done automatically at the token level. Any easy fix to annotate spans from token labels?

Thanks a lot in advance!

**Comment by OleksandrKorovii** [comment]
@Lingepumpe How to use your solution with JsonlCorpus or should I write my own corpus?

**Comment by Lingepumpe** [comment]
Quick fix is to use flair-0.10. If 0.11 is needed, the fastest work-around that I can think of is to change JsonlCorpus (create FixedJsonlCorpus using a copy of the code), where span labeling is used.

The real fix, which is to fix the issues with token labeling BIO labels, is a bit more complicated and I have not submitted a PR for it yet.

**Comment by ksksho** [comment]
You can use BIO and BIOES in flair-0.11.x.
When you want to use BIO, you have to use correct BIO, namely, "O", "B-label", "I-label".
If you use another labels like "-X-", flair throw the above error.

**Comment by grinay** [comment]
For those who faces the same issue here is the fixed version of jsonl corpus.
https://gist.github.com/grinay/c6ace94383b55970f175ae4d1afbe010
@Lingepumpe  do you think it is a correct fix?
There is two lines fixed:
```
        # Tag all other token as Outer (O)
        for token in sentence:
            if token.get_label(self.label_type).value == "":
                **token.add_label(self.label_type, "O")**
```

```
# Add IOB tags
        **sentence[start_idx : end_idx + 1].add_label(self.label_type, f"{label}")**
        
        # prefix = "B"
        # for token in sentence[start_idx : end_idx + 1]:
        #     token.add_label(self.label_type, f"{prefix}-{label}")
        #     prefix = "I"
```

**Comment by zynos** [comment]
The fix from @grinay helped! Hope the fix will be merged soon.

**Comment by alanakbik** [comment]
The JSONCorpus should already be fixed in master branch, see https://github.com/flairNLP/flair/pull/2863
