### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by faz9** [flairNLP/flair#2864]
I was trying to train FLAIR for NER and i had this bug.
  File "FLAIR1.py", line 37, in <module>
    trainer.train('resources/taggers/example-ner',learning_rate=0.1,mini_batch_size=16,max_epochs=10,main_evaluation_metric=("macro avg", "f1-score"),embeddings_storage_mode="cpu")
  File "flair/trainers/trainer.py", line 624, in train
    dev_eval_result = self.model.evaluate(
  File "flair/nn/model.py", line 236, in evaluate
    loss_and_count = self.predict(
  File "flair/models/sequence_tagger_model.py", line 487, in predict
    loss = self._calculate_loss(features, gold_labels)
  File "flair/models/sequence_tagger_model.py", line 336, in _calculate_loss
    [
  File "flair/models/sequence_tagger_model.py", line 337, in <listcomp>
    self.label_dictionary.get_idx_for_item(label[0])
  File "flair/data.py", line 90, in get_idx_for_item
    raise IndexError
IndexError

Any ideas to solve this please?

**Comment by jv92** [comment]
Maybe check label_dictionary when you create the model
Are u using corpus.make_label_dictionary()?

**Comment by mct-lrh** [comment]
I am encountering the same issue.  It happens specifically when the epoch ends and testing begins.

Here is how I load my corpus:
```
# define columns
columns = {0: 'text', 1: 'ner'}

# this is the folder in which train, test and dev files reside
data_folder = 'C:/Users/laura/anaconda3/envs/allen/'

# 1. init a corpus using column format, data folder and the names of the train, dev and test files
corpus: Corpus = ColumnCorpus(data_folder, columns,
                              train_file='NER_train.txt',
                              test_file='NER_test.txt',
                              dev_file='NER_dev.txt')
```

Make label_dict:
```
# 2. what label do we want to predict?
label_type = 'ner'

# 3. make the label dictionary from the corpus
label_dict = corpus.make_label_dictionary(label_type=label_type)
```

What it looks like:
```
print(label_dict)
Dictionary with 18 tags: <unk>, VEH, LOC, TOOL, ORG, PERSON, QUANTITY, EVENT, DIRECTION, TIME, CARDINAL, FAC, ORDINAL, DATE, PRODUCT, LANGUAGE, , MONEY
```

The model and training are copy-and-pasted from the[ tutorial](https://flairnlp.github.io/docs/tutorial-training/how-to-train-sequence-tagger).

The error:
```
2023-04-07 12:02:10,779 Testing using last state of model ...
  6%|████▋                                                                             | 7/122 [00:21<06:06,  3.19s/it]2023-04-07 12:02:34,889 The string 'S-DIR' is not in dictionary! Dictionary contains only: ['O', 'S-VEH', 'B-VEH', 'E-VEH', 'I-VEH', 'S-LOC', 'B-LOC', 'E-LOC', 'I-LOC', 'S-TOOL', 'B-TOOL', 'E-TOOL', 'I-TOOL', 'S-ORG', 'B-ORG', 'E-ORG', 'I-ORG', 'S-PERSON', 'B-PERSON', 'E-PERSON', 'I-PERSON', 'S-QUANTITY', 'B-QUANTITY', 'E-QUANTITY', 'I-QUANTITY', 'S-EVENT', 'B-EVENT', 'E-EVENT', 'I-EVENT', 'S-DIRECTION', 'B-DIRECTION', 'E-DIRECTION', 'I-DIRECTION', 'S-TIME', 'B-TIME', 'E-TIME', 'I-TIME', 'S-CARDINAL', 'B-CARDINAL', 'E-CARDINAL', 'I-CARDINAL', 'S-FAC', 'B-FAC', 'E-FAC', 'I-FAC', 'S-ORDINAL', 'B-ORDINAL', 'E-ORDINAL', 'I-ORDINAL', 'S-DATE', 'B-DATE', 'E-DATE', 'I-DATE', 'S-', 'B-', 'E-', 'I-']
2023-04-07 12:02:34,889 You can create a Dictionary that handles unknown items with an <unk>-key by setting add_unk = True in the construction.
  6%|████▋                                                                             | 7/122 [00:24<06:35,  3.44s/it]
Traceback (most recent call last):
  File "flair_finetune.py", line 67, in <module>
    mini_batch_chunk_size=1,  # remove this parameter to speed up computation if you have a big GPU
  File "C:\Users\laura\anaconda3\envs\allen\lib\site-packages\flair\trainers\trainer.py", line 909, in fine_tune
    **trainer_args,
  File "C:\Users\laura\anaconda3\envs\allen\lib\site-packages\flair\trainers\trainer.py", line 842, in train
    exclude_labels=exclude_labels,
  File "C:\Users\laura\anaconda3\envs\allen\lib\site-packages\flair\trainers\trainer.py", line 943, in final_test
    exclude_labels=exclude_labels,
  File "C:\Users\laura\anaconda3\envs\allen\lib\site-packages\flair\nn\model.py", line 241, in evaluate
    return_loss=True,
  File "C:\Users\laura\anaconda3\envs\allen\lib\site-packages\flair\models\sequence_tagger_model.py", line 487, in predict
    loss = self._calculate_loss(features, gold_labels)
  File "C:\Users\laura\anaconda3\envs\allen\lib\site-packages\flair\models\sequence_tagger_model.py", line 340, in _calculate_loss
    for label in labels
  File "C:\Users\laura\anaconda3\envs\allen\lib\site-packages\flair\models\sequence_tagger_model.py", line 340, in <listcomp>
    for label in labels
  File "C:\Users\laura\anaconda3\envs\allen\lib\site-packages\flair\data.py", line 90, in get_idx_for_item
    raise IndexError
IndexError
```
