### ISSUE TITLE
Problem loading fasttext with ngram features

### ISSUE THREAD

**Issue by DanrunFR** [flairNLP/flair#3008]
Hello, 

I trained a fasttext model on a custom corpus with ngram features, but I can't seem to load it with flair whereas the same .bin file works with gensim. 

More precisely, I do this on gensim and I can get a vector out of a total random word.
```
from gensim.models.fasttext import FastText
model = FastText.load('embeddings/fasttext_fr_wac/ft_frwac.300.bin')
model.wv['qqqqqfds']
# some vector
```
Then I try to load the same file with FastTextEmbeddings:
```
from flair.embeddings import FastTextEmbeddings
embeddings = FastTextEmbeddings('embeddings/fasttext_fr_wac/ft_frwac.300.bin')
```

And there would be a NotImplementedError message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/home/cao/.conda/envs/bilstm_crf_Study/lib/python3.8/site-packages/flair/embeddings/token.py", line 945, in __init__
    self.precomputed_word_embeddings: gensim.models.FastText = gensim.models.FastText.load_fasttext_format(
  File "/share/home/cao/.conda/envs/bilstm_crf_Study/lib/python3.8/site-packages/gensim/utils.py", line 1522, in new_func1
    return func(*args, **kwargs)
  File "/share/home/cao/.conda/envs/bilstm_crf_Study/lib/python3.8/site-packages/gensim/models/fasttext.py", line 580, in load_fasttext_format
    return load_facebook_model(model_file, encoding=encoding)
  File "/share/home/cao/.conda/envs/bilstm_crf_Study/lib/python3.8/site-packages/gensim/models/fasttext.py", line 728, in load_facebook_model
    return _load_fasttext_format(path, encoding=encoding, full_model=True)
  File "/share/home/cao/.conda/envs/bilstm_crf_Study/lib/python3.8/site-packages/gensim/models/fasttext.py", line 808, in _load_fasttext_format
    m = gensim.models._fasttext_bin.load(fin, encoding=encoding, full_model=full_model)
  File "/share/home/cao/.conda/envs/bilstm_crf_Study/lib/python3.8/site-packages/gensim/models/_fasttext_bin.py", line 345, in load
    raw_vocab, vocab_size, nwords, ntokens = _load_vocab(fin, new_format, encoding=encoding)
  File "/share/home/cao/.conda/envs/bilstm_crf_Study/lib/python3.8/site-packages/gensim/models/_fasttext_bin.py", line 198, in _load_vocab
    raise NotImplementedError("Supervised fastText models are not supported")
NotImplementedError: Supervised fastText models are not supported
```
I also tried with WordEmbeddings just in case, and it didn't work, as expected:
```
embeddings = WordEmbeddings('embeddings/fasttext_fr_wac/ft_frwac.300.bin')

# output
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/home/cao/.conda/envs/bilstm_crf_Study/lib/python3.8/site-packages/flair/embeddings/token.py", line 213, in __init__
    precomputed_word_embeddings = gensim.models.KeyedVectors.load_word2vec_format(
  File "/share/home/cao/.conda/envs/bilstm_crf_Study/lib/python3.8/site-packages/gensim/models/keyedvectors.py", line 1723, in load_word2vec_format
    return _load_word2vec_format(
  File "/share/home/cao/.conda/envs/bilstm_crf_Study/lib/python3.8/site-packages/gensim/models/keyedvectors.py", line 2062, in _load_word2vec_format
    header = utils.to_unicode(fin.readline(), encoding=encoding)
  File "/share/home/cao/.conda/envs/bilstm_crf_Study/lib/python3.8/site-packages/gensim/utils.py", line 365, in any2unicode
    return str(text, encoding, errors=errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: Linux Debian 5.10.149-2
 - Version [e.g. flair-0.3.2]: flair 0.11.3, gensim 4.2.0

Both libraries are in the same virtual environment so there shouldn't be conflicts. Is there something I'm doing wrong ? Maybe I missed a parameter or something ?

Thank you in advance for your help.

**Comment by helpmefindaname** [comment]
Hi @DanrunFR 
Flair uses `gensim.models.FastText.load_fasttext_format` to load the model. It expects a model saved by using `fasttext_model.save_facebook_model(...)`

**Comment by DanrunFR** [comment]
That is the exact solution thank you very much !!
