### ISSUE TITLE
Error found

### ISSUE THREAD

**Issue by Dhanachandra** [flairNLP/flair#3037]
2022-12-22 18:13:03,186 epoch 1 - iter 143/1434 - loss 0.91632178 - samples/sec: 16.81 - lr: 0.100000
Traceback (most recent call last):
  File "trainer.py", line 48, in <module>
    max_epochs=150)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flair/trainers/trainer.py", line 500, in train
    loss = self.model.forward_loss(batch_step)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 270, in forward_loss
    scores, gold_labels = self.forward(sentences)  # type: ignore
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 290, in forward
    sentence_tensor = sentence_tensor[length_indices]
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by helpmefindaname** [comment]
Hi @Dhanachandra 
as your output says: `CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.`

we would need you run your code again with that environment variable set to provide a real stacktrace. Besides that, it would be good if you find an minimal example (code + training data) to reproduce this error.
