### ISSUE TITLE
[Question]: How do I load a previously generated model in TextClassifier?

### ISSUE THREAD

**Issue by Daremitsu1** [flairNLP/flair#3126]
### Question

I have used arcgis learn.text to import TextClassifier in order for creating a Machine learning module. Now I want to use the same model in Streamlitfor creating an interface for re-use and displaying the predictions.

Code for the app I am creating:
```
import streamlit as st
import os
from arcgis.learn.text import TextClassifier, SequenceToSequence
import pickle

with st.sidebar:
    st.image('https://www.attomdata.com/wp-content/uploads/2021/05/ATTOM-main-full-1000.jpg')
    st.title("AutoAttom")
    st.info("This project application will help in text classification and sequence to sequence labelling")

# Text Classifier Section
st.title("Text Classifier")
user_input = st.text_input(""" """)
if user_input:
    model_folder = os.path.join('models', 'text-classifier')
    print(os.listdir(model_folder))
    model = TextClassifier.load(model_folder, name_or_path=model_folder)
    st.write(model.predict(user_input))
```

I am getting the error as follows:
```
Traceback (most recent call last):
  File "d:\python projects\attom\text2seq\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "D:\Python Projects\ATTOM\app.py", line 17, in <module>
    model = TextClassifier.load(model_folder, name_or_path=model_folder)
  File "d:\python projects\attom\text2seq\lib\site-packages\arcgis\learn\text\_text_classifier.py", line 298, in load
    return super().load(name_or_path)
TypeError: super(type, obj): obj must be an instance or subtype of type
```

My models folder tree directory is as follows:
```
D:.
├───seq2seq_unfrozen8E_bleu_88
│   │   model_metrics.html
│   │   seq2seq_unfrozen8E_bleu_88.emd
│   │   seq2seq_unfrozen8E_bleu_88.pth
│   │
│   └───ModelCharacteristics
│           loss_graph.png
│           sample_results.html
│
└───text-classifier
    │   model_metrics.html
    │   text-classifier.dlpk
    │   text-classifier.emd
    │   text-classifier.pth
    │
    └───ModelCharacteristics
            loss_graph.png
            sample_results.html
```

All solutions I am seeing is asking to create the model in the code interface again and then load. Is there a way to load the model from previously generated?

**Comment by helpmefindaname** [comment]
Hi @Daremitsu1
notice that you are not using a `Flair ` model, so we cannot help you with your `arcgis` issue.
