### ISSUE TITLE
[Bug]: LSTM-based Sequence Taggers cannot be loaded with PyTorch 2.0

### ISSUE THREAD

**Issue by alanakbik** [flairNLP/flair#3158]
### Describe the bug

Loading LSTM-based models with PyTorch 2.0 throws "AttributeError: 'LSTM' object has no attribute '_flat_weights'"

### To Reproduce

```python
from flair.models import SequenceTagger

tagger = SequenceTagger.load("ner-ontonotes")
```

### Expected behaivor

The model should load

### Logs and Stack traces

```stacktrace
Traceback (most recent call last):
  File "/home/alan/PycharmProjects/flair/local_quick.py", line 4, in <module>
    tagger = SequenceTagger.load("ner-ontonotes")
  File "/home/alan/PycharmProjects/flair/flair/models/sequence_tagger_model.py", line 1034, in load
    return cast("SequenceTagger", super().load(model_path=model_path))
  File "/home/alan/PycharmProjects/flair/flair/nn/model.py", line 559, in load
    return cast("Classifier", super().load(model_path=model_path))
  File "/home/alan/PycharmProjects/flair/flair/nn/model.py", line 191, in load
    state = load_torch_state(model_file)
  File "/home/alan/PycharmProjects/flair/flair/file_utils.py", line 359, in load_torch_state
    return torch.load(f, map_location="cpu")
  File "/home/alan/.environments/flair-torch-2.0/lib/python3.8/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/alan/.environments/flair-torch-2.0/lib/python3.8/site-packages/torch/serialization.py", line 1043, in _legacy_load
    result = unpickler.load()
  File "/home/alan/.environments/flair-torch-2.0/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 325, in __setstate__
    for w in self._flat_weights]
  File "/home/alan/.environments/flair-torch-2.0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LSTM' object has no attribute '_flat_weights'
```

### Environment

Current master branch, PyTorch 2.0

**Comment by cprocak3** [comment]
I am getting the same error but with a different use case. What version of flair are you using? I'm at 0.8

**Comment by alanakbik** [comment]
I am testing on current master. This only seems to affect very old models in Flair, so as a fix I am retraining them on the newest version.
