### ISSUE TITLE
[Question]: Cannot even run base flair code that's been provided on huggingface

### ISSUE THREAD

**Issue by firdovsi9** [flairNLP/flair#3174]
### Question

```
from flair.data import Sentence
from flair.models import SequenceTagger

tagger = SequenceTagger.load("flair/ner-english-ontonotes-large")

sentence = Sentence("On September 1st George won 1 dollar while watching Game of Thrones.")

tagger.predict(sentence)

print(sentence)

print('The following NER tags are found:')

for entity in sentence.get_spans('ner'):
    print(entity)

```

**It outputs this error:**
```
Traceback (most recent call last):
  File "/Users/firdovsihasanzada/PycharmProjects/pythonProject4/main.py", line 5, in <module>
    tagger = SequenceTagger.load("flair/ner-english-ontonotes-large")
  File "/Users/firdovsihasanzada/PycharmProjects/pythonProject4/venv/lib/python3.8/site-packages/flair/models/sequence_tagger_model.py", line 1034, in load
    return cast("SequenceTagger", super().load(model_path=model_path))
  File "/Users/firdovsihasanzada/PycharmProjects/pythonProject4/venv/lib/python3.8/site-packages/flair/nn/model.py", line 559, in load
    return cast("Classifier", super().load(model_path=model_path))
  File "/Users/firdovsihasanzada/PycharmProjects/pythonProject4/venv/lib/python3.8/site-packages/flair/nn/model.py", line 191, in load
    state = load_torch_state(model_file)
  File "/Users/firdovsihasanzada/PycharmProjects/pythonProject4/venv/lib/python3.8/site-packages/flair/file_utils.py", line 355, in load_torch_state
    return torch.load(f, map_location="cpu")
  File "/Users/firdovsihasanzada/PycharmProjects/pythonProject4/venv/lib/python3.8/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/Users/firdovsihasanzada/PycharmProjects/pythonProject4/venv/lib/python3.8/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Comment by helpmefindaname** [comment]
Hi @firdovsi9 
this looks like you had an issue while downloading the model. Can you delete the file from your huggingface cache and download it again?
