### ISSUE TITLE
[Bug]: ModuleNotFoundError: 'flair.trainers.plugins.functional' on git-installed master

### ISSUE THREAD

**Issue by helpmefindaname** [flairNLP/flair#3199]
### Describe the bug

When installing the flair master branch via pypi & git, we get an ModuleNotFound error.

### To Reproduce

```python
exec("pip install git+https://github.com/flairNLP/flair.git")
from flair.models import TARSClassifier
```

### Expected behavior

I can import any module and use flair normally.

### Logs and Stack traces

```stacktrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bened\anaconda3\envs\steepmc_clf\lib\site-packages\flair\__init__.py", line 28, in <module>
    from . import (  # noqa: E402 import after setting device
  File "C:\Users\bened\anaconda3\envs\steepmc_clf\lib\site-packages\flair\trainers\__init__.py", line 2, in <module>
    from .trainer import ModelTrainer
  File "C:\Users\bened\anaconda3\envs\steepmc_clf\lib\site-packages\flair\trainers\trainer.py", line 19, in <module>
    from flair.trainers.plugins import (
  File "C:\Users\bened\anaconda3\envs\steepmc_clf\lib\site-packages\flair\trainers\plugins\__init__.py", line 2, in <module>
    from .functional.amp import AmpPlugin
ModuleNotFoundError: No module named 'flair.trainers.plugins.functional'
```

### Additional Context

I suppose this happens due to missing `__init__.py` files in https://github.com/flairNLP/flair/tree/master/flair/trainers/plugins/functional and https://github.com/flairNLP/flair/tree/master/flair/trainers/plugins/loggers 

leading to those folders not being recognized as modules and therefore won't be found/installed as code.

##### Pytorch
2.0.0+cu117
##### flair
`ModuleNotFoundError`
##### Transformers
4.28.1
#### GPU
True

**Comment by helpmefindaname** [comment]
Thank you, @plonerma
