### ISSUE TITLE
[Question]: Sample code for transformer document embeddings

### ISSUE THREAD

**Issue by konrad0101** [flairNLP/flair#3286]
### Question

Would it be possible to see a sample implementation of transformer document embeddings in Flair, specifically with the `TransformerDocumentEmbeddings` or `SentenceTransformerDocumentEmbeddings` class, when using SequenceTagger? When I run the sample code provided for SequenceTagger (https://flairnlp.github.io/docs/tutorial-training/how-to-train-sequence-tagger) but with document embeddings rather than word embeddings, I get exceptions that I'm not able to resolve due to their vagueness. 

Modified sample code from https://flairnlp.github.io/docs/tutorial-training/how-to-train-sequence-tagger: 

```python
from flair.datasets import FEWNERD  # I replaced the CONLL_03 dataset from the sample code since it wasn't found in the flair.datasets folder
from flair.embeddings import TransformerDocumentEmbeddings
from flair.models import SequenceTagger
from flair.trainers import ModelTrainer

# 1. get the corpus
corpus = FEWNERD()
print(corpus)

# 2. what label do we want to predict?
label_type = 'ner'

# 3. make the label dictionary from the corpus
label_dict = corpus.make_label_dictionary(label_type=label_type, add_unk=False)
print(label_dict)

# 4. initialize fine-tuneable transformer embeddings WITH document context
embeddings = TransformerDocumentEmbeddings(model="roberta-base")

# 5. initialize bare-bones sequence tagger (no CRF, no RNN, no reprojection)
tagger = SequenceTagger(hidden_size=256,
                        embeddings=embeddings,
                        tag_dictionary=label_dict,
                        tag_type='ner',
                        use_crf=False,
                        use_rnn=False,
                        reproject_embeddings=False,
                        )

# 6. initialize trainer
trainer = ModelTrainer(tagger, corpus)

# 7. run fine-tuning
trainer.fine_tune('resources/taggers/sota-ner-flert',
                  learning_rate=5.0e-6,
                  mini_batch_size=4,
                  )
```

Exception:

```
Traceback (most recent call last):
  File "/home/ubuntu/sample.py", line 34, in <module>
    trainer.fine_tune('resources/taggers/sota-ner-flert',
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/sample-wj8GFpIk-py3.11/lib/python3.11/site-packages/flair/trainers/trainer.py", line 245, in fine_tune
    return self.train_custom(
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/sample-wj8GFpIk-py3.11/lib/python3.11/site-packages/flair/trainers/trainer.py", line 570, in train_custom
    loss, datapoint_count = self.model.forward_loss(batch_step)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/sample-wj8GFpIk-py3.11/lib/python3.11/site-packages/flair/models/sequence_tagger_model.py", line 274, in forward_loss
    sentence_tensor, lengths = self._prepare_tensors(sentences)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/sample-wj8GFpIk-py3.11/lib/python3.11/site-packages/flair/models/sequence_tagger_model.py", line 287, in _prepare_tensors
    lengths, sentence_tensor = self._make_padded_tensor_for_batch(sentences)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/sample-wj8GFpIk-py3.11/lib/python3.11/site-packages/flair/models/sequence_tagger_model.py", line 355, in _make_padded_tensor_for_batch
    sentence_tensor = torch.cat(all_embs).view(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[4, 36, 768]' is invalid for input of size 39936
```

**Comment by helpmefindaname** [comment]
Hi @konrad0101 
you can look at the tutorial after: https://flairnlp.github.io/docs/tutorial-training/how-to-train-text-classifier
notice that you cannot use a DocumentEmbedding to train a SequenceTagger, as the SequenceTagger expects a TokenEmbedding. DocumentEmbeddings are for Tasks like TextClassification, where you want to have a single embedding for the whole Document/Sentence

**Comment by konrad0101** [comment]
Understood, thanks! I was missing the part that `SequenceTagger` expects `TokenEmbeddings` and not `DocumentEmbeddings`. I see it now in the codebase and it's clear: 

```python
class SequenceTagger(flair.nn.Classifier[Sentence]):
    def __init__(
        self,
        embeddings: TokenEmbeddings,  

```
