### ISSUE TITLE
[Question]: I am unable to load any classifier model from flair

### ISSUE THREAD

**Issue by nikkiris** [flairNLP/flair#3343]
### Question

A few days ago I was doing some experiments with flair to do NER, and it was working. Today I went back to it and the following error appears.Things I've changed in the meantime:

- changed from using my cpu by default to using the gpu
-  installed spacy and trained their model to recognize fruits, (installed spacy-transformers, spacy-lookups-data and downloaded some of their models to do this)
- installed cupy
- installed chardet and cchardet
- removed pytorch-cpu and installed pytorch-cuda=12.1, as well as torchvision and torchaudio
- installed sentence-transformers

Now what I get just from trying to load the model is this:
```
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from flair.nn import Classifier
>>> ner = Classifier.load('ner-english-ontonotes-large')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vspelbrink/miniconda3/envs/robostackenv/lib/python3.9/site-packages/flair/nn/model.py", line 559, in load
    return cast("Classifier", super().load(model_path=model_path))
  File "/home/vspelbrink/miniconda3/envs/robostackenv/lib/python3.9/site-packages/flair/nn/model.py", line 165, in load
    state = model_path if isinstance(model_path, dict) else load_torch_state(str(model_path))
  File "/home/vspelbrink/miniconda3/envs/robostackenv/lib/python3.9/site-packages/flair/file_utils.py", line 358, in load_torch_state
    f = load_big_file(model_file)
  File "/home/vspelbrink/miniconda3/envs/robostackenv/lib/python3.9/site-packages/flair/file_utils.py", line 50, in load_big_file
    with open(f, "rb") as f_in:
FileNotFoundError: [Errno 2] No such file or directory: 'ner-english-ontonotes-large
```

Which of these things I did in the mean time could be the culprit? I have seen the lines where the error is, and it seems it skips downloading the model and tries to load the torch state which I assume is like a cached version of the model. I have tried deleting the ~/.flair/models contents and reinstalling flair. but nothing has worked so far.

Some help would be welcome. Thanks in advance.

**Comment by nikkiris** [comment]
Turns out when I install the package using conda in my environment, it doesn't work, it seems some of the changes in master [42ea3f6](https://github.com/flairNLP/flair/commit/42ea3f6854eba04387c38045f160c18bdaac07dc) are not available in the release available on the repositories conda installs flair from.

**Comment by nikkiris** [comment]
Turns out when I install the package using conda in my environment, it doesn't work, it seems some of the changes in master [42ea3f6](https://github.com/flairNLP/flair/commit/42ea3f6854eba04387c38045f160c18bdaac07dc) are not available in the release available on the repositories conda installs flair from.
