### ISSUE TITLE
RuntimeError: std::bad_alloc

### ISSUE THREAD

**Issue by emrul** [flairNLP/flair#619]
I've marked this as a question as I think it might be related to my usage (or to PyTorch)

When I enable checkpointing I get the crash below (PyTorch Version:  1.0.0.dev20190321)
```
Traceback (most recent call last):
  File "test.py", line 53, in <module>
    checkpoint=True)
  File "/home/paperspace/anaconda3/envs/flair/lib/python3.7/site-packages/flair/trainers/trainer.py", line 230, in train
    epoch + 1, train_loss)
  File "/home/paperspace/anaconda3/envs/flair/lib/python3.7/site-packages/flair/models/sequence_tagger_model.py", line 205, in save_checkpoint
    self.save_torch_model(model_state, str(model_file), self.pickle_module)
  File "/home/paperspace/anaconda3/envs/flair/lib/python3.7/site-packages/flair/models/sequence_tagger_model.py", line 168, in save_torch_model
    torch.save(model_state, str(model_file), pickle_protocol=pickle_protocol)
  File "/home/paperspace/anaconda3/envs/flair/lib/python3.7/site-packages/torch/serialization.py", line 224, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/paperspace/anaconda3/envs/flair/lib/python3.7/site-packages/torch/serialization.py", line 149, in _with_file_like
    return body(f)
  File "/home/paperspace/anaconda3/envs/flair/lib/python3.7/site-packages/torch/serialization.py", line 224, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/paperspace/anaconda3/envs/flair/lib/python3.7/site-packages/torch/serialization.py", line 303, in _save
    serialized_storages[key]._write_file(f, _should_read_directly(f))
RuntimeError: std::bad_alloc
```

If I downsample my dataset to, say, 10% this error does not occur.

Any idea on what I can do to solve this?

**Comment by stefan-it** [comment]
@emrul do you have any chance to update your PyTorch version? Try to use 1.0.1 :)

**Comment by emrul** [comment]
@stefan-it - thanks - I am using the nightly and the problem seems gone now.
